# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  GH_CLI_APK_VERSION: '{{default "" .GH_CLI_APK_VERSION}}'
  COPILOT_CLI_VERSION: '{{default "0.0.421" .COPILOT_CLI_VERSION}}'

tasks:
  gqlgen:
    desc: Generate GraphQL client code
    cmds:
    - go tool gqlgen generate

  build-api:
    desc: Build the API container image
    cmds:
    - docker compose -f docker-compose.yml build api

  build-worker:
    desc: Build the worker container image
    cmds:
    - docker compose -f docker-compose.yml build --build-arg GH_CLI_APK_VERSION={{.GH_CLI_APK_VERSION}} --build-arg COPILOT_CLI_VERSION={{.COPILOT_CLI_VERSION}} worker

  compose-up:
    desc: Start the application using Docker Compose
    cmds:
    - docker-compose -f docker-compose.yml up -d --build

  destroy:
    desc: Stop and remove all containers, networks, with optional additional arguments
    cmds:
    - docker-compose -f docker-compose.yml down --remove-orphans {{ .CLI_ARGS }}
