# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  gqlgen:
    desc: Generate GraphQL client code
    cmds:
    - go tool gqlgen generate

  compose-up:
    desc: Start the application using Docker Compose
    cmds:
    - docker-compose -f docker-compose.yml up -d --build

  destroy:
    desc: Stop and remove all containers, networks, with optional additional arguments
    cmds:
    - docker-compose -f docker-compose.yml down --remove-orphans {{ .CLI_ARGS }}
