package taskboard

import "testing"

func TestBuildBoardFromResponse(t *testing.T) {
	response := `{"status":"in-progress","epics":[{"id":"e1","title":"Epic","status":"completed","tasks":[{"id":"t1","title":"Task","status":"not-started"}]}],"created_at":"2026-01-01T00:00:00Z","updated_at":"2026-01-01T00:00:00Z"}`

	board, err := BuildBoardFromResponse("run-1", response)
	if err != nil {
		t.Fatalf("unexpected build error: %v", err)
	}
	if board.BoardID != "run-1" || board.RunID != "run-1" {
		t.Fatalf("expected run ids to be applied, got board_id=%s run_id=%s", board.BoardID, board.RunID)
	}
}

func TestBuildBoardFromResponseRejectsInvalidPayload(t *testing.T) {
	_, err := BuildBoardFromResponse("run-1", "not-json")
	if err == nil {
		t.Fatalf("expected parse error")
	}
}

func TestBuildBoardFromResponseInitializesTimestampsFromApplication(t *testing.T) {
	response := `{"status":"in-progress","epics":[{"id":"e1","title":"Epic","status":"completed","tasks":[{"id":"t1","title":"Task","status":"not-started"}]}],"created_at":"2020-01-01T00:00:00Z","updated_at":"2020-01-01T00:00:00Z"}`

	board, err := BuildBoardFromResponse("run-1", response)
	if err != nil {
		t.Fatalf("unexpected build error: %v", err)
	}

	if board.CreatedAt.IsZero() || board.UpdatedAt.IsZero() {
		t.Fatalf("expected board timestamps to be initialized")
	}
	if !board.CreatedAt.Equal(board.UpdatedAt) {
		t.Fatalf("expected initial board created_at and updated_at to match")
	}
	if board.CreatedAt.Format("2006-01-02") == "2020-01-01" {
		t.Fatalf("expected board timestamp to be generated by application")
	}

	epic := board.Epics[0]
	if epic.CreatedAt.IsZero() || epic.UpdatedAt.IsZero() {
		t.Fatalf("expected epic timestamps to be initialized")
	}
	if !epic.CreatedAt.Equal(board.CreatedAt) || !epic.UpdatedAt.Equal(board.UpdatedAt) {
		t.Fatalf("expected epic timestamps to match board initial timestamp")
	}

	task := epic.Tasks[0]
	if task.CreatedAt.IsZero() || task.UpdatedAt.IsZero() {
		t.Fatalf("expected task timestamps to be initialized")
	}
	if !task.CreatedAt.Equal(board.CreatedAt) || !task.UpdatedAt.Equal(board.UpdatedAt) {
		t.Fatalf("expected task timestamps to match board initial timestamp")
	}
}
