// Mocks generated by Mockito 5.4.6 from annotations
// in agentic_worktrees/test/support/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:agentic_worktrees/shared/graph/typed/api.dart' as _i4;
import 'package:agentic_worktrees/shared/graph/typed/models.dart' as _i2;
import 'package:graphql/client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultPolicies_1 extends _i1.SmartFake
    implements _i3.DefaultPolicies {
  _FakeDefaultPolicies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLink_2 extends _i1.SmartFake implements _i3.Link {
  _FakeLink_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLCache_3 extends _i1.SmartFake implements _i3.GraphQLCache {
  _FakeGraphQLCache_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryManager_4 extends _i1.SmartFake implements _i3.QueryManager {
  _FakeQueryManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLClient_5 extends _i1.SmartFake implements _i3.GraphQLClient {
  _FakeGraphQLClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObservableQuery_6<TParsed1> extends _i1.SmartFake
    implements _i3.ObservableQuery<TParsed1> {
  _FakeObservableQuery_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryResult_7<TParsed1 extends Object?> extends _i1.SmartFake
    implements _i3.QueryResult<TParsed1> {
  _FakeQueryResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ControlPlaneApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockControlPlaneApi extends _i1.Mock implements _i4.ControlPlaneApi {
  @override
  _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>> sessions({
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessions, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>>.value(
                  _FakeApiResult_0<List<_i2.SessionSummary>>(
                    this,
                    Invocation.method(#sessions, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>>.value(
                  _FakeApiResult_0<List<_i2.SessionSummary>>(
                    this,
                    Invocation.method(#sessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>> workflowJobs({
    required String? runID,
    String? taskID,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#workflowJobs, [], {
              #runID: runID,
              #taskID: taskID,
              #limit: limit,
            }),
            returnValue: _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>>.value(
              _FakeApiResult_0<List<_i2.WorkflowJob>>(
                this,
                Invocation.method(#workflowJobs, [], {
                  #runID: runID,
                  #taskID: taskID,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>>.value(
                  _FakeApiResult_0<List<_i2.WorkflowJob>>(
                    this,
                    Invocation.method(#workflowJobs, [], {
                      #runID: runID,
                      #taskID: taskID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>> supervisorHistory({
    required String? runID,
    required String? taskID,
    required String? jobID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#supervisorHistory, [], {
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>>.value(
                  _FakeApiResult_0<List<_i2.SupervisorDecision>>(
                    this,
                    Invocation.method(#supervisorHistory, [], {
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>>.value(
                  _FakeApiResult_0<List<_i2.SupervisorDecision>>(
                    this,
                    Invocation.method(#supervisorHistory, [], {
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>>);

  @override
  _i5.Future<_i2.ApiResult<String>> approveIssueIntake({
    required String? runID,
    required String? taskID,
    required String? jobID,
    required String? projectID,
    required String? source,
    required String? issueReference,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveIssueIntake, [], {
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
              #projectID: projectID,
              #source: source,
              #issueReference: issueReference,
              #approvedBy: approvedBy,
            }),
            returnValue: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#approveIssueIntake, [], {
                  #runID: runID,
                  #taskID: taskID,
                  #jobID: jobID,
                  #projectID: projectID,
                  #source: source,
                  #issueReference: issueReference,
                  #approvedBy: approvedBy,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#approveIssueIntake, [], {
                  #runID: runID,
                  #taskID: taskID,
                  #jobID: jobID,
                  #projectID: projectID,
                  #source: source,
                  #issueReference: issueReference,
                  #approvedBy: approvedBy,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<String>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>> projectSetups({
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#projectSetups, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>>.value(
                  _FakeApiResult_0<List<_i2.ProjectSetupConfig>>(
                    this,
                    Invocation.method(#projectSetups, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>>.value(
                  _FakeApiResult_0<List<_i2.ProjectSetupConfig>>(
                    this,
                    Invocation.method(#projectSetups, [], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>> upsertProjectSetup({
    required String? projectID,
    required String? projectName,
    required String? scmProvider,
    required List<String>? repositoryURLs,
    required String? scmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProjectSetup, [], {
              #projectID: projectID,
              #projectName: projectName,
              #scmProvider: scmProvider,
              #repositoryURLs: repositoryURLs,
              #scmToken: scmToken,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>.value(
                  _FakeApiResult_0<_i2.ProjectSetupConfig>(
                    this,
                    Invocation.method(#upsertProjectSetup, [], {
                      #projectID: projectID,
                      #projectName: projectName,
                      #scmProvider: scmProvider,
                      #repositoryURLs: repositoryURLs,
                      #scmToken: scmToken,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>.value(
                  _FakeApiResult_0<_i2.ProjectSetupConfig>(
                    this,
                    Invocation.method(#upsertProjectSetup, [], {
                      #projectID: projectID,
                      #projectName: projectName,
                      #scmProvider: scmProvider,
                      #repositoryURLs: repositoryURLs,
                      #scmToken: scmToken,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> sessionActivityStream({
    required String? runID,
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessionActivityStream, [], {
              #runID: runID,
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>> workerSessions({
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#workerSessions, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>>.value(
                  _FakeApiResult_0<List<_i2.WorkerSession>>(
                    this,
                    Invocation.method(#workerSessions, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>>.value(
                  _FakeApiResult_0<List<_i2.WorkerSession>>(
                    this,
                    Invocation.method(#workerSessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.WorkerSettings>> workerSettings() =>
      (super.noSuchMethod(
            Invocation.method(#workerSettings, []),
            returnValue: _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
              _FakeApiResult_0<_i2.WorkerSettings>(
                this,
                Invocation.method(#workerSettings, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
                  _FakeApiResult_0<_i2.WorkerSettings>(
                    this,
                    Invocation.method(#workerSettings, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.WorkerSettings>> updateWorkerSettings({
    required int? heartbeatIntervalSeconds,
    required int? responseDeadlineSeconds,
    required int? staleAfterSeconds,
    required int? drainTimeoutSeconds,
    required int? terminateTimeoutSeconds,
    required int? rogueThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkerSettings, [], {
              #heartbeatIntervalSeconds: heartbeatIntervalSeconds,
              #responseDeadlineSeconds: responseDeadlineSeconds,
              #staleAfterSeconds: staleAfterSeconds,
              #drainTimeoutSeconds: drainTimeoutSeconds,
              #terminateTimeoutSeconds: terminateTimeoutSeconds,
              #rogueThreshold: rogueThreshold,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
              _FakeApiResult_0<_i2.WorkerSettings>(
                this,
                Invocation.method(#updateWorkerSettings, [], {
                  #heartbeatIntervalSeconds: heartbeatIntervalSeconds,
                  #responseDeadlineSeconds: responseDeadlineSeconds,
                  #staleAfterSeconds: staleAfterSeconds,
                  #drainTimeoutSeconds: drainTimeoutSeconds,
                  #terminateTimeoutSeconds: terminateTimeoutSeconds,
                  #rogueThreshold: rogueThreshold,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
                  _FakeApiResult_0<_i2.WorkerSettings>(
                    this,
                    Invocation.method(#updateWorkerSettings, [], {
                      #heartbeatIntervalSeconds: heartbeatIntervalSeconds,
                      #responseDeadlineSeconds: responseDeadlineSeconds,
                      #staleAfterSeconds: staleAfterSeconds,
                      #drainTimeoutSeconds: drainTimeoutSeconds,
                      #terminateTimeoutSeconds: terminateTimeoutSeconds,
                      #rogueThreshold: rogueThreshold,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> workerSessionStream({
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#workerSessionStream, [], {
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);
}

/// A class which mocks [GraphQLClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphQLClient extends _i1.Mock implements _i3.GraphQLClient {
  @override
  _i3.DefaultPolicies get defaultPolicies =>
      (super.noSuchMethod(
            Invocation.getter(#defaultPolicies),
            returnValue: _FakeDefaultPolicies_1(
              this,
              Invocation.getter(#defaultPolicies),
            ),
            returnValueForMissingStub: _FakeDefaultPolicies_1(
              this,
              Invocation.getter(#defaultPolicies),
            ),
          )
          as _i3.DefaultPolicies);

  @override
  _i3.Link get link =>
      (super.noSuchMethod(
            Invocation.getter(#link),
            returnValue: _FakeLink_2(this, Invocation.getter(#link)),
            returnValueForMissingStub: _FakeLink_2(
              this,
              Invocation.getter(#link),
            ),
          )
          as _i3.Link);

  @override
  _i3.GraphQLCache get cache =>
      (super.noSuchMethod(
            Invocation.getter(#cache),
            returnValue: _FakeGraphQLCache_3(this, Invocation.getter(#cache)),
            returnValueForMissingStub: _FakeGraphQLCache_3(
              this,
              Invocation.getter(#cache),
            ),
          )
          as _i3.GraphQLCache);

  @override
  _i3.QueryManager get queryManager =>
      (super.noSuchMethod(
            Invocation.getter(#queryManager),
            returnValue: _FakeQueryManager_4(
              this,
              Invocation.getter(#queryManager),
            ),
            returnValueForMissingStub: _FakeQueryManager_4(
              this,
              Invocation.getter(#queryManager),
            ),
          )
          as _i3.QueryManager);

  @override
  set defaultPolicies(_i3.DefaultPolicies? value) => super.noSuchMethod(
    Invocation.setter(#defaultPolicies, value),
    returnValueForMissingStub: null,
  );

  @override
  set queryManager(_i3.QueryManager? value) => super.noSuchMethod(
    Invocation.setter(#queryManager, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.GraphQLClient copyWith({
    _i3.Link? link,
    _i3.GraphQLCache? cache,
    _i3.DefaultPolicies? defaultPolicies,
    bool? alwaysRebroadcast,
    _i3.DeepEqualsFn? deepEquals,
    _i3.AsyncDeepEqualsFn? asyncDeepEquals,
    bool? deduplicatePollers = false,
    Duration? queryRequestTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #link: link,
              #cache: cache,
              #defaultPolicies: defaultPolicies,
              #alwaysRebroadcast: alwaysRebroadcast,
              #deepEquals: deepEquals,
              #asyncDeepEquals: asyncDeepEquals,
              #deduplicatePollers: deduplicatePollers,
              #queryRequestTimeout: queryRequestTimeout,
            }),
            returnValue: _FakeGraphQLClient_5(
              this,
              Invocation.method(#copyWith, [], {
                #link: link,
                #cache: cache,
                #defaultPolicies: defaultPolicies,
                #alwaysRebroadcast: alwaysRebroadcast,
                #deepEquals: deepEquals,
                #asyncDeepEquals: asyncDeepEquals,
                #deduplicatePollers: deduplicatePollers,
                #queryRequestTimeout: queryRequestTimeout,
              }),
            ),
            returnValueForMissingStub: _FakeGraphQLClient_5(
              this,
              Invocation.method(#copyWith, [], {
                #link: link,
                #cache: cache,
                #defaultPolicies: defaultPolicies,
                #alwaysRebroadcast: alwaysRebroadcast,
                #deepEquals: deepEquals,
                #asyncDeepEquals: asyncDeepEquals,
                #deduplicatePollers: deduplicatePollers,
                #queryRequestTimeout: queryRequestTimeout,
              }),
            ),
          )
          as _i3.GraphQLClient);

  @override
  _i3.ObservableQuery<TParsed> watchQuery<TParsed>(
    _i3.WatchQueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuery, [options]),
            returnValue: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchQuery, [options]),
            ),
            returnValueForMissingStub: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchQuery, [options]),
            ),
          )
          as _i3.ObservableQuery<TParsed>);

  @override
  _i3.ObservableQuery<TParsed> watchMutation<TParsed>(
    _i3.WatchQueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMutation, [options]),
            returnValue: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchMutation, [options]),
            ),
            returnValueForMissingStub: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchMutation, [options]),
            ),
          )
          as _i3.ObservableQuery<TParsed>);

  @override
  _i5.Future<_i3.QueryResult<TParsed>> query<TParsed>(
    _i3.QueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#query, [options]),
            returnValue: _i5.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_7<TParsed>(
                this,
                Invocation.method(#query, [options]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_7<TParsed>(
                    this,
                    Invocation.method(#query, [options]),
                  ),
                ),
          )
          as _i5.Future<_i3.QueryResult<TParsed>>);

  @override
  _i5.Future<_i3.QueryResult<TParsed>> mutate<TParsed>(
    _i3.MutationOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mutate, [options]),
            returnValue: _i5.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_7<TParsed>(
                this,
                Invocation.method(#mutate, [options]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_7<TParsed>(
                    this,
                    Invocation.method(#mutate, [options]),
                  ),
                ),
          )
          as _i5.Future<_i3.QueryResult<TParsed>>);

  @override
  _i5.Stream<_i3.QueryResult<TParsed>> subscribe<TParsed>(
    _i3.SubscriptionOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [options]),
            returnValue: _i5.Stream<_i3.QueryResult<TParsed>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i3.QueryResult<TParsed>>.empty(),
          )
          as _i5.Stream<_i3.QueryResult<TParsed>>);

  @override
  _i5.Future<_i3.QueryResult<TParsed>> fetchMore<TParsed>(
    _i3.FetchMoreOptions? fetchMoreOptions, {
    required _i3.QueryOptions<TParsed>? originalOptions,
    required _i3.QueryResult<TParsed>? previousResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMore,
              [fetchMoreOptions],
              {
                #originalOptions: originalOptions,
                #previousResult: previousResult,
              },
            ),
            returnValue: _i5.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_7<TParsed>(
                this,
                Invocation.method(
                  #fetchMore,
                  [fetchMoreOptions],
                  {
                    #originalOptions: originalOptions,
                    #previousResult: previousResult,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_7<TParsed>(
                    this,
                    Invocation.method(
                      #fetchMore,
                      [fetchMoreOptions],
                      {
                        #originalOptions: originalOptions,
                        #previousResult: previousResult,
                      },
                    ),
                  ),
                ),
          )
          as _i5.Future<_i3.QueryResult<TParsed>>);

  @override
  Map<String, dynamic>? readQuery(
    _i3.Request? request, {
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readQuery, [request], {#optimistic: optimistic}),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  Map<String, dynamic>? readFragment(
    _i3.FragmentRequest? fragmentRequest, {
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readFragment,
              [fragmentRequest],
              {#optimistic: optimistic},
            ),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  void writeQuery(
    _i3.Request? request, {
    required Map<String, dynamic>? data,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeQuery,
      [request],
      {#data: data, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void writeFragment(
    _i3.FragmentRequest? fragmentRequest, {
    bool? broadcast = true,
    required Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeFragment,
      [fragmentRequest],
      {#broadcast: broadcast, #data: data},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i3.QueryResult<Object?>?>>? resetStore({
    bool? refetchQueries = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetStore, [], {
              #refetchQueries: refetchQueries,
            }),
            returnValueForMissingStub: null,
          )
          as _i5.Future<List<_i3.QueryResult<Object?>?>>?);
}
