// Mocks generated by Mockito 5.4.6 from annotations
// in agentic_repositories/test/support/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:agentic_repositories/shared/graph/typed/api.dart' as _i4;
import 'package:agentic_repositories/shared/graph/typed/models.dart' as _i2;
import 'package:graphql/client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultPolicies_1 extends _i1.SmartFake
    implements _i3.DefaultPolicies {
  _FakeDefaultPolicies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLink_2 extends _i1.SmartFake implements _i3.Link {
  _FakeLink_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLCache_3 extends _i1.SmartFake implements _i3.GraphQLCache {
  _FakeGraphQLCache_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryManager_4 extends _i1.SmartFake implements _i3.QueryManager {
  _FakeQueryManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLClient_5 extends _i1.SmartFake implements _i3.GraphQLClient {
  _FakeGraphQLClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObservableQuery_6<TParsed1> extends _i1.SmartFake
    implements _i3.ObservableQuery<TParsed1> {
  _FakeObservableQuery_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryResult_7<TParsed1 extends Object?> extends _i1.SmartFake
    implements _i3.QueryResult<TParsed1> {
  _FakeQueryResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ControlPlaneApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockControlPlaneApi extends _i1.Mock implements _i4.ControlPlaneApi {
  @override
  _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>> sessions({
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessions, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>>.value(
                  _FakeApiResult_0<List<_i2.SessionSummary>>(
                    this,
                    Invocation.method(#sessions, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>>.value(
                  _FakeApiResult_0<List<_i2.SessionSummary>>(
                    this,
                    Invocation.method(#sessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.SessionSummary>>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>> workflowJobs({
    required String? runID,
    String? taskID,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#workflowJobs, [], {
              #runID: runID,
              #taskID: taskID,
              #limit: limit,
            }),
            returnValue: _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>>.value(
              _FakeApiResult_0<List<_i2.WorkflowJob>>(
                this,
                Invocation.method(#workflowJobs, [], {
                  #runID: runID,
                  #taskID: taskID,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>>.value(
                  _FakeApiResult_0<List<_i2.WorkflowJob>>(
                    this,
                    Invocation.method(#workflowJobs, [], {
                      #runID: runID,
                      #taskID: taskID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.WorkflowJob>>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>> supervisorHistory({
    required String? runID,
    required String? taskID,
    required String? jobID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#supervisorHistory, [], {
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>>.value(
                  _FakeApiResult_0<List<_i2.SupervisorDecision>>(
                    this,
                    Invocation.method(#supervisorHistory, [], {
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>>.value(
                  _FakeApiResult_0<List<_i2.SupervisorDecision>>(
                    this,
                    Invocation.method(#supervisorHistory, [], {
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.SupervisorDecision>>>);

  @override
  _i5.Future<_i2.ApiResult<String>> approveIssueIntake({
    required String? runID,
    required String? taskID,
    required String? jobID,
    required String? projectID,
    required String? source,
    required String? issueReference,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveIssueIntake, [], {
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
              #projectID: projectID,
              #source: source,
              #issueReference: issueReference,
              #approvedBy: approvedBy,
            }),
            returnValue: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#approveIssueIntake, [], {
                  #runID: runID,
                  #taskID: taskID,
                  #jobID: jobID,
                  #projectID: projectID,
                  #source: source,
                  #issueReference: issueReference,
                  #approvedBy: approvedBy,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#approveIssueIntake, [], {
                  #runID: runID,
                  #taskID: taskID,
                  #jobID: jobID,
                  #projectID: projectID,
                  #source: source,
                  #issueReference: issueReference,
                  #approvedBy: approvedBy,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<String>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>> projectSetups({
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#projectSetups, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>>.value(
                  _FakeApiResult_0<List<_i2.ProjectSetupConfig>>(
                    this,
                    Invocation.method(#projectSetups, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>>.value(
                  _FakeApiResult_0<List<_i2.ProjectSetupConfig>>(
                    this,
                    Invocation.method(#projectSetups, [], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.ProjectSetupConfig>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>> projectSetup({
    required String? projectID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#projectSetup, [], {#projectID: projectID}),
            returnValue:
                _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>.value(
                  _FakeApiResult_0<_i2.ProjectSetupConfig>(
                    this,
                    Invocation.method(#projectSetup, [], {
                      #projectID: projectID,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>.value(
                  _FakeApiResult_0<_i2.ProjectSetupConfig>(
                    this,
                    Invocation.method(#projectSetup, [], {
                      #projectID: projectID,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>> upsertProjectSetup({
    required String? projectID,
    required String? projectName,
    required String? scmProvider,
    required List<String>? repositoryURLs,
    required String? scmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProjectSetup, [], {
              #projectID: projectID,
              #projectName: projectName,
              #scmProvider: scmProvider,
              #repositoryURLs: repositoryURLs,
              #scmToken: scmToken,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>.value(
                  _FakeApiResult_0<_i2.ProjectSetupConfig>(
                    this,
                    Invocation.method(#upsertProjectSetup, [], {
                      #projectID: projectID,
                      #projectName: projectName,
                      #scmProvider: scmProvider,
                      #repositoryURLs: repositoryURLs,
                      #scmToken: scmToken,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>.value(
                  _FakeApiResult_0<_i2.ProjectSetupConfig>(
                    this,
                    Invocation.method(#upsertProjectSetup, [], {
                      #projectID: projectID,
                      #projectName: projectName,
                      #scmProvider: scmProvider,
                      #repositoryURLs: repositoryURLs,
                      #scmToken: scmToken,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.ProjectSetupConfig>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.ProjectDocument>>> projectDocuments({
    required String? projectID,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#projectDocuments, [], {
              #projectID: projectID,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.ProjectDocument>>>.value(
                  _FakeApiResult_0<List<_i2.ProjectDocument>>(
                    this,
                    Invocation.method(#projectDocuments, [], {
                      #projectID: projectID,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.ProjectDocument>>>.value(
                  _FakeApiResult_0<List<_i2.ProjectDocument>>(
                    this,
                    Invocation.method(#projectDocuments, [], {
                      #projectID: projectID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.ProjectDocument>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.ProjectDocumentUploadTicket>>
  requestProjectDocumentUpload({
    required String? projectID,
    required String? fileName,
    required String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestProjectDocumentUpload, [], {
              #projectID: projectID,
              #fileName: fileName,
              #contentType: contentType,
            }),
            returnValue:
                _i5.Future<
                  _i2.ApiResult<_i2.ProjectDocumentUploadTicket>
                >.value(
                  _FakeApiResult_0<_i2.ProjectDocumentUploadTicket>(
                    this,
                    Invocation.method(#requestProjectDocumentUpload, [], {
                      #projectID: projectID,
                      #fileName: fileName,
                      #contentType: contentType,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.ApiResult<_i2.ProjectDocumentUploadTicket>
                >.value(
                  _FakeApiResult_0<_i2.ProjectDocumentUploadTicket>(
                    this,
                    Invocation.method(#requestProjectDocumentUpload, [], {
                      #projectID: projectID,
                      #fileName: fileName,
                      #contentType: contentType,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.ProjectDocumentUploadTicket>>);

  @override
  _i5.Future<_i2.ApiResult<void>> uploadProjectDocumentBytes({
    required String? uploadURL,
    required _i6.Uint8List? bytes,
    required String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProjectDocumentBytes, [], {
              #uploadURL: uploadURL,
              #bytes: bytes,
              #contentType: contentType,
            }),
            returnValue: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#uploadProjectDocumentBytes, [], {
                  #uploadURL: uploadURL,
                  #bytes: bytes,
                  #contentType: contentType,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#uploadProjectDocumentBytes, [], {
                  #uploadURL: uploadURL,
                  #bytes: bytes,
                  #contentType: contentType,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<void>>);

  @override
  _i5.Future<_i2.ApiResult<void>> deleteProjectDocument({
    required String? projectID,
    required String? documentID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProjectDocument, [], {
              #projectID: projectID,
              #documentID: documentID,
            }),
            returnValue: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#deleteProjectDocument, [], {
                  #projectID: projectID,
                  #documentID: documentID,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#deleteProjectDocument, [], {
                  #projectID: projectID,
                  #documentID: documentID,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<void>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.IngestionRunTicket>> runIngestionAgent({
    required String? projectID,
    required String? taskboardName,
    List<String>? selectedDocumentIDs,
    String? userPrompt,
    Map<String, String>? repositorySourceBranches,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#runIngestionAgent, [], {
              #projectID: projectID,
              #taskboardName: taskboardName,
              #selectedDocumentIDs: selectedDocumentIDs,
              #userPrompt: userPrompt,
              #repositorySourceBranches: repositorySourceBranches,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<_i2.IngestionRunTicket>>.value(
                  _FakeApiResult_0<_i2.IngestionRunTicket>(
                    this,
                    Invocation.method(#runIngestionAgent, [], {
                      #projectID: projectID,
                      #taskboardName: taskboardName,
                      #selectedDocumentIDs: selectedDocumentIDs,
                      #userPrompt: userPrompt,
                      #repositorySourceBranches: repositorySourceBranches,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.IngestionRunTicket>>.value(
                  _FakeApiResult_0<_i2.IngestionRunTicket>(
                    this,
                    Invocation.method(#runIngestionAgent, [], {
                      #projectID: projectID,
                      #taskboardName: taskboardName,
                      #selectedDocumentIDs: selectedDocumentIDs,
                      #userPrompt: userPrompt,
                      #repositorySourceBranches: repositorySourceBranches,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.IngestionRunTicket>>);

  @override
  _i5.Future<_i2.ApiResult<String>> refineIngestionPrompt({
    required String? projectID,
    required String? taskboardName,
    String? userPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refineIngestionPrompt, [], {
              #projectID: projectID,
              #taskboardName: taskboardName,
              #userPrompt: userPrompt,
            }),
            returnValue: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#refineIngestionPrompt, [], {
                  #projectID: projectID,
                  #taskboardName: taskboardName,
                  #userPrompt: userPrompt,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#refineIngestionPrompt, [], {
                  #projectID: projectID,
                  #taskboardName: taskboardName,
                  #userPrompt: userPrompt,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<String>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.ProjectRepositoryBranchOption>>>
  projectRepositoryBranches({required String? projectID}) =>
      (super.noSuchMethod(
            Invocation.method(#projectRepositoryBranches, [], {
              #projectID: projectID,
            }),
            returnValue:
                _i5.Future<
                  _i2.ApiResult<List<_i2.ProjectRepositoryBranchOption>>
                >.value(
                  _FakeApiResult_0<List<_i2.ProjectRepositoryBranchOption>>(
                    this,
                    Invocation.method(#projectRepositoryBranches, [], {
                      #projectID: projectID,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.ApiResult<List<_i2.ProjectRepositoryBranchOption>>
                >.value(
                  _FakeApiResult_0<List<_i2.ProjectRepositoryBranchOption>>(
                    this,
                    Invocation.method(#projectRepositoryBranches, [], {
                      #projectID: projectID,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.ApiResult<List<_i2.ProjectRepositoryBranchOption>>
          >);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.TaskboardModel>>> taskboards({
    required String? projectID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#taskboards, [], {#projectID: projectID}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.TaskboardModel>>>.value(
                  _FakeApiResult_0<List<_i2.TaskboardModel>>(
                    this,
                    Invocation.method(#taskboards, [], {#projectID: projectID}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.TaskboardModel>>>.value(
                  _FakeApiResult_0<List<_i2.TaskboardModel>>(
                    this,
                    Invocation.method(#taskboards, [], {#projectID: projectID}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.TaskboardModel>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> taskboard({
    required String? projectID,
    required String? boardID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#taskboard, [], {
              #projectID: projectID,
              #boardID: boardID,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#taskboard, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#taskboard, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> createTaskboard({
    required String? projectID,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskboard, [], {
              #projectID: projectID,
              #name: name,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#createTaskboard, [], {
                  #projectID: projectID,
                  #name: name,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#createTaskboard, [], {
                      #projectID: projectID,
                      #name: name,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> updateTaskboard({
    required String? projectID,
    required String? boardID,
    required String? name,
    required String? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskboard, [], {
              #projectID: projectID,
              #boardID: boardID,
              #name: name,
              #state: state,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#updateTaskboard, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #name: name,
                  #state: state,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#updateTaskboard, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #name: name,
                      #state: state,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<void>> deleteTaskboard({
    required String? projectID,
    required String? boardID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskboard, [], {
              #projectID: projectID,
              #boardID: boardID,
            }),
            returnValue: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#deleteTaskboard, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#deleteTaskboard, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<void>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> createTaskboardEpic({
    required String? projectID,
    required String? boardID,
    required String? title,
    String? objective,
    List<String>? repositoryIDs = const [],
    List<String>? deliverables = const [],
    required String? state,
    int? rank = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskboardEpic, [], {
              #projectID: projectID,
              #boardID: boardID,
              #title: title,
              #objective: objective,
              #repositoryIDs: repositoryIDs,
              #deliverables: deliverables,
              #state: state,
              #rank: rank,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#createTaskboardEpic, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #title: title,
                  #objective: objective,
                  #repositoryIDs: repositoryIDs,
                  #deliverables: deliverables,
                  #state: state,
                  #rank: rank,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#createTaskboardEpic, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #title: title,
                      #objective: objective,
                      #repositoryIDs: repositoryIDs,
                      #deliverables: deliverables,
                      #state: state,
                      #rank: rank,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> updateTaskboardEpic({
    required String? projectID,
    required String? boardID,
    required String? epicID,
    required String? title,
    String? objective,
    List<String>? repositoryIDs = const [],
    List<String>? deliverables = const [],
    required String? state,
    int? rank = 0,
    List<String>? dependsOnEpicIDs = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskboardEpic, [], {
              #projectID: projectID,
              #boardID: boardID,
              #epicID: epicID,
              #title: title,
              #objective: objective,
              #repositoryIDs: repositoryIDs,
              #deliverables: deliverables,
              #state: state,
              #rank: rank,
              #dependsOnEpicIDs: dependsOnEpicIDs,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#updateTaskboardEpic, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #epicID: epicID,
                  #title: title,
                  #objective: objective,
                  #repositoryIDs: repositoryIDs,
                  #deliverables: deliverables,
                  #state: state,
                  #rank: rank,
                  #dependsOnEpicIDs: dependsOnEpicIDs,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#updateTaskboardEpic, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #epicID: epicID,
                      #title: title,
                      #objective: objective,
                      #repositoryIDs: repositoryIDs,
                      #deliverables: deliverables,
                      #state: state,
                      #rank: rank,
                      #dependsOnEpicIDs: dependsOnEpicIDs,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> deleteTaskboardEpic({
    required String? projectID,
    required String? boardID,
    required String? epicID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskboardEpic, [], {
              #projectID: projectID,
              #boardID: boardID,
              #epicID: epicID,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#deleteTaskboardEpic, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #epicID: epicID,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#deleteTaskboardEpic, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #epicID: epicID,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> createTaskboardTask({
    required String? projectID,
    required String? boardID,
    required String? epicID,
    required String? title,
    String? description,
    List<String>? repositoryIDs = const [],
    List<String>? deliverables = const [],
    required String? taskType,
    required String? state,
    int? rank = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskboardTask, [], {
              #projectID: projectID,
              #boardID: boardID,
              #epicID: epicID,
              #title: title,
              #description: description,
              #repositoryIDs: repositoryIDs,
              #deliverables: deliverables,
              #taskType: taskType,
              #state: state,
              #rank: rank,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#createTaskboardTask, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #epicID: epicID,
                  #title: title,
                  #description: description,
                  #repositoryIDs: repositoryIDs,
                  #deliverables: deliverables,
                  #taskType: taskType,
                  #state: state,
                  #rank: rank,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#createTaskboardTask, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #epicID: epicID,
                      #title: title,
                      #description: description,
                      #repositoryIDs: repositoryIDs,
                      #deliverables: deliverables,
                      #taskType: taskType,
                      #state: state,
                      #rank: rank,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> updateTaskboardTask({
    required String? projectID,
    required String? boardID,
    required String? epicID,
    required String? taskID,
    required String? title,
    String? description,
    List<String>? repositoryIDs = const [],
    List<String>? deliverables = const [],
    required String? taskType,
    required String? state,
    int? rank = 0,
    List<String>? dependsOnTaskIDs = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskboardTask, [], {
              #projectID: projectID,
              #boardID: boardID,
              #epicID: epicID,
              #taskID: taskID,
              #title: title,
              #description: description,
              #repositoryIDs: repositoryIDs,
              #deliverables: deliverables,
              #taskType: taskType,
              #state: state,
              #rank: rank,
              #dependsOnTaskIDs: dependsOnTaskIDs,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#updateTaskboardTask, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #epicID: epicID,
                  #taskID: taskID,
                  #title: title,
                  #description: description,
                  #repositoryIDs: repositoryIDs,
                  #deliverables: deliverables,
                  #taskType: taskType,
                  #state: state,
                  #rank: rank,
                  #dependsOnTaskIDs: dependsOnTaskIDs,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#updateTaskboardTask, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #epicID: epicID,
                      #taskID: taskID,
                      #title: title,
                      #description: description,
                      #repositoryIDs: repositoryIDs,
                      #deliverables: deliverables,
                      #taskType: taskType,
                      #state: state,
                      #rank: rank,
                      #dependsOnTaskIDs: dependsOnTaskIDs,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.TaskboardModel>> deleteTaskboardTask({
    required String? projectID,
    required String? boardID,
    required String? taskID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskboardTask, [], {
              #projectID: projectID,
              #boardID: boardID,
              #taskID: taskID,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
              _FakeApiResult_0<_i2.TaskboardModel>(
                this,
                Invocation.method(#deleteTaskboardTask, [], {
                  #projectID: projectID,
                  #boardID: boardID,
                  #taskID: taskID,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>.value(
                  _FakeApiResult_0<_i2.TaskboardModel>(
                    this,
                    Invocation.method(#deleteTaskboardTask, [], {
                      #projectID: projectID,
                      #boardID: boardID,
                      #taskID: taskID,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.TaskboardModel>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> sessionActivityStream({
    required String? runID,
    String? projectID,
    String? taskID,
    String? jobID,
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessionActivityStream, [], {
              #runID: runID,
              #projectID: projectID,
              #taskID: taskID,
              #jobID: jobID,
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> pipelineEventsStream({
    required String? projectID,
    String? runID,
    String? taskID,
    String? jobID,
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pipelineEventsStream, [], {
              #projectID: projectID,
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> taskboardStream({
    required String? projectID,
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#taskboardStream, [], {
              #projectID: projectID,
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>> projectEvents({
    required String? projectID,
    int? fromOffset = 0,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#projectEvents, [], {
              #projectID: projectID,
              #fromOffset: fromOffset,
              #limit: limit,
            }),
            returnValue: _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>>.value(
              _FakeApiResult_0<List<_i2.StreamEvent>>(
                this,
                Invocation.method(#projectEvents, [], {
                  #projectID: projectID,
                  #fromOffset: fromOffset,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>>.value(
                  _FakeApiResult_0<List<_i2.StreamEvent>>(
                    this,
                    Invocation.method(#projectEvents, [], {
                      #projectID: projectID,
                      #fromOffset: fromOffset,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>> pipelineEvents({
    required String? projectID,
    String? runID,
    String? taskID,
    String? jobID,
    int? fromOffset = 0,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pipelineEvents, [], {
              #projectID: projectID,
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
              #fromOffset: fromOffset,
              #limit: limit,
            }),
            returnValue: _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>>.value(
              _FakeApiResult_0<List<_i2.StreamEvent>>(
                this,
                Invocation.method(#pipelineEvents, [], {
                  #projectID: projectID,
                  #runID: runID,
                  #taskID: taskID,
                  #jobID: jobID,
                  #fromOffset: fromOffset,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>>.value(
                  _FakeApiResult_0<List<_i2.StreamEvent>>(
                    this,
                    Invocation.method(#pipelineEvents, [], {
                      #projectID: projectID,
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                      #fromOffset: fromOffset,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.StreamEvent>>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> projectEventsStream({
    required String? projectID,
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#projectEventsStream, [], {
              #projectID: projectID,
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.LifecycleSessionSnapshotModel>>>
  lifecycleSessionSnapshots({
    required String? projectID,
    String? pipelineType,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lifecycleSessionSnapshots, [], {
              #projectID: projectID,
              #pipelineType: pipelineType,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.ApiResult<List<_i2.LifecycleSessionSnapshotModel>>
                >.value(
                  _FakeApiResult_0<List<_i2.LifecycleSessionSnapshotModel>>(
                    this,
                    Invocation.method(#lifecycleSessionSnapshots, [], {
                      #projectID: projectID,
                      #pipelineType: pipelineType,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.ApiResult<List<_i2.LifecycleSessionSnapshotModel>>
                >.value(
                  _FakeApiResult_0<List<_i2.LifecycleSessionSnapshotModel>>(
                    this,
                    Invocation.method(#lifecycleSessionSnapshots, [], {
                      #projectID: projectID,
                      #pipelineType: pipelineType,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i2.ApiResult<List<_i2.LifecycleSessionSnapshotModel>>
          >);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.LifecycleHistoryEventModel>>>
  lifecycleSessionHistory({
    required String? projectID,
    required String? sessionID,
    int? fromEventSeq = 0,
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lifecycleSessionHistory, [], {
              #projectID: projectID,
              #sessionID: sessionID,
              #fromEventSeq: fromEventSeq,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.ApiResult<List<_i2.LifecycleHistoryEventModel>>
                >.value(
                  _FakeApiResult_0<List<_i2.LifecycleHistoryEventModel>>(
                    this,
                    Invocation.method(#lifecycleSessionHistory, [], {
                      #projectID: projectID,
                      #sessionID: sessionID,
                      #fromEventSeq: fromEventSeq,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.ApiResult<List<_i2.LifecycleHistoryEventModel>>
                >.value(
                  _FakeApiResult_0<List<_i2.LifecycleHistoryEventModel>>(
                    this,
                    Invocation.method(#lifecycleSessionHistory, [], {
                      #projectID: projectID,
                      #sessionID: sessionID,
                      #fromEventSeq: fromEventSeq,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.LifecycleHistoryEventModel>>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.LifecycleTreeNodeModel>>>
  lifecycleTreeNodes({
    required String? projectID,
    String? pipelineType,
    String? runID,
    String? taskID,
    String? jobID,
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lifecycleTreeNodes, [], {
              #projectID: projectID,
              #pipelineType: pipelineType,
              #runID: runID,
              #taskID: taskID,
              #jobID: jobID,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<
                  _i2.ApiResult<List<_i2.LifecycleTreeNodeModel>>
                >.value(
                  _FakeApiResult_0<List<_i2.LifecycleTreeNodeModel>>(
                    this,
                    Invocation.method(#lifecycleTreeNodes, [], {
                      #projectID: projectID,
                      #pipelineType: pipelineType,
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.ApiResult<List<_i2.LifecycleTreeNodeModel>>
                >.value(
                  _FakeApiResult_0<List<_i2.LifecycleTreeNodeModel>>(
                    this,
                    Invocation.method(#lifecycleTreeNodes, [], {
                      #projectID: projectID,
                      #pipelineType: pipelineType,
                      #runID: runID,
                      #taskID: taskID,
                      #jobID: jobID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.LifecycleTreeNodeModel>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.InterventionMetricsModel>> interventionMetrics({
    required String? projectID,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#interventionMetrics, [], {
              #projectID: projectID,
              #limit: limit,
            }),
            returnValue:
                _i5.Future<_i2.ApiResult<_i2.InterventionMetricsModel>>.value(
                  _FakeApiResult_0<_i2.InterventionMetricsModel>(
                    this,
                    Invocation.method(#interventionMetrics, [], {
                      #projectID: projectID,
                      #limit: limit,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.InterventionMetricsModel>>.value(
                  _FakeApiResult_0<_i2.InterventionMetricsModel>(
                    this,
                    Invocation.method(#interventionMetrics, [], {
                      #projectID: projectID,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.InterventionMetricsModel>>);

  @override
  _i5.Future<_i2.ApiResult<String>> applyManualIntervention({
    required String? projectID,
    required String? sessionID,
    required String? action,
    required String? reason,
    required String? actorID,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyManualIntervention, [], {
              #projectID: projectID,
              #sessionID: sessionID,
              #action: action,
              #reason: reason,
              #actorID: actorID,
              #force: force,
            }),
            returnValue: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#applyManualIntervention, [], {
                  #projectID: projectID,
                  #sessionID: sessionID,
                  #action: action,
                  #reason: reason,
                  #actorID: actorID,
                  #force: force,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#applyManualIntervention, [], {
                  #projectID: projectID,
                  #sessionID: sessionID,
                  #action: action,
                  #reason: reason,
                  #actorID: actorID,
                  #force: force,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<String>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>> workerSessions({
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#workerSessions, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>>.value(
                  _FakeApiResult_0<List<_i2.WorkerSession>>(
                    this,
                    Invocation.method(#workerSessions, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>>.value(
                  _FakeApiResult_0<List<_i2.WorkerSession>>(
                    this,
                    Invocation.method(#workerSessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i2.WorkerSession>>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.WorkerSettings>> workerSettings() =>
      (super.noSuchMethod(
            Invocation.method(#workerSettings, []),
            returnValue: _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
              _FakeApiResult_0<_i2.WorkerSettings>(
                this,
                Invocation.method(#workerSettings, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
                  _FakeApiResult_0<_i2.WorkerSettings>(
                    this,
                    Invocation.method(#workerSettings, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>);

  @override
  _i5.Future<_i2.ApiResult<_i2.WorkerSettings>> updateWorkerSettings({
    required int? heartbeatIntervalSeconds,
    required int? responseDeadlineSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkerSettings, [], {
              #heartbeatIntervalSeconds: heartbeatIntervalSeconds,
              #responseDeadlineSeconds: responseDeadlineSeconds,
            }),
            returnValue: _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
              _FakeApiResult_0<_i2.WorkerSettings>(
                this,
                Invocation.method(#updateWorkerSettings, [], {
                  #heartbeatIntervalSeconds: heartbeatIntervalSeconds,
                  #responseDeadlineSeconds: responseDeadlineSeconds,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>.value(
                  _FakeApiResult_0<_i2.WorkerSettings>(
                    this,
                    Invocation.method(#updateWorkerSettings, [], {
                      #heartbeatIntervalSeconds: heartbeatIntervalSeconds,
                      #responseDeadlineSeconds: responseDeadlineSeconds,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<_i2.WorkerSettings>>);

  @override
  _i5.Stream<_i2.ApiResult<_i2.StreamEvent>> workerSessionStream({
    int? fromOffset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#workerSessionStream, [], {
              #fromOffset: fromOffset,
            }),
            returnValue: _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>.empty(),
          )
          as _i5.Stream<_i2.ApiResult<_i2.StreamEvent>>);
}

/// A class which mocks [GraphQLClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphQLClient extends _i1.Mock implements _i3.GraphQLClient {
  @override
  _i3.DefaultPolicies get defaultPolicies =>
      (super.noSuchMethod(
            Invocation.getter(#defaultPolicies),
            returnValue: _FakeDefaultPolicies_1(
              this,
              Invocation.getter(#defaultPolicies),
            ),
            returnValueForMissingStub: _FakeDefaultPolicies_1(
              this,
              Invocation.getter(#defaultPolicies),
            ),
          )
          as _i3.DefaultPolicies);

  @override
  _i3.Link get link =>
      (super.noSuchMethod(
            Invocation.getter(#link),
            returnValue: _FakeLink_2(this, Invocation.getter(#link)),
            returnValueForMissingStub: _FakeLink_2(
              this,
              Invocation.getter(#link),
            ),
          )
          as _i3.Link);

  @override
  _i3.GraphQLCache get cache =>
      (super.noSuchMethod(
            Invocation.getter(#cache),
            returnValue: _FakeGraphQLCache_3(this, Invocation.getter(#cache)),
            returnValueForMissingStub: _FakeGraphQLCache_3(
              this,
              Invocation.getter(#cache),
            ),
          )
          as _i3.GraphQLCache);

  @override
  _i3.QueryManager get queryManager =>
      (super.noSuchMethod(
            Invocation.getter(#queryManager),
            returnValue: _FakeQueryManager_4(
              this,
              Invocation.getter(#queryManager),
            ),
            returnValueForMissingStub: _FakeQueryManager_4(
              this,
              Invocation.getter(#queryManager),
            ),
          )
          as _i3.QueryManager);

  @override
  set defaultPolicies(_i3.DefaultPolicies? value) => super.noSuchMethod(
    Invocation.setter(#defaultPolicies, value),
    returnValueForMissingStub: null,
  );

  @override
  set queryManager(_i3.QueryManager? value) => super.noSuchMethod(
    Invocation.setter(#queryManager, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.GraphQLClient copyWith({
    _i3.Link? link,
    _i3.GraphQLCache? cache,
    _i3.DefaultPolicies? defaultPolicies,
    bool? alwaysRebroadcast,
    _i3.DeepEqualsFn? deepEquals,
    _i3.AsyncDeepEqualsFn? asyncDeepEquals,
    bool? deduplicatePollers = false,
    Duration? queryRequestTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #link: link,
              #cache: cache,
              #defaultPolicies: defaultPolicies,
              #alwaysRebroadcast: alwaysRebroadcast,
              #deepEquals: deepEquals,
              #asyncDeepEquals: asyncDeepEquals,
              #deduplicatePollers: deduplicatePollers,
              #queryRequestTimeout: queryRequestTimeout,
            }),
            returnValue: _FakeGraphQLClient_5(
              this,
              Invocation.method(#copyWith, [], {
                #link: link,
                #cache: cache,
                #defaultPolicies: defaultPolicies,
                #alwaysRebroadcast: alwaysRebroadcast,
                #deepEquals: deepEquals,
                #asyncDeepEquals: asyncDeepEquals,
                #deduplicatePollers: deduplicatePollers,
                #queryRequestTimeout: queryRequestTimeout,
              }),
            ),
            returnValueForMissingStub: _FakeGraphQLClient_5(
              this,
              Invocation.method(#copyWith, [], {
                #link: link,
                #cache: cache,
                #defaultPolicies: defaultPolicies,
                #alwaysRebroadcast: alwaysRebroadcast,
                #deepEquals: deepEquals,
                #asyncDeepEquals: asyncDeepEquals,
                #deduplicatePollers: deduplicatePollers,
                #queryRequestTimeout: queryRequestTimeout,
              }),
            ),
          )
          as _i3.GraphQLClient);

  @override
  _i3.ObservableQuery<TParsed> watchQuery<TParsed>(
    _i3.WatchQueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuery, [options]),
            returnValue: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchQuery, [options]),
            ),
            returnValueForMissingStub: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchQuery, [options]),
            ),
          )
          as _i3.ObservableQuery<TParsed>);

  @override
  _i3.ObservableQuery<TParsed> watchMutation<TParsed>(
    _i3.WatchQueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMutation, [options]),
            returnValue: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchMutation, [options]),
            ),
            returnValueForMissingStub: _FakeObservableQuery_6<TParsed>(
              this,
              Invocation.method(#watchMutation, [options]),
            ),
          )
          as _i3.ObservableQuery<TParsed>);

  @override
  _i5.Future<_i3.QueryResult<TParsed>> query<TParsed>(
    _i3.QueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#query, [options]),
            returnValue: _i5.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_7<TParsed>(
                this,
                Invocation.method(#query, [options]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_7<TParsed>(
                    this,
                    Invocation.method(#query, [options]),
                  ),
                ),
          )
          as _i5.Future<_i3.QueryResult<TParsed>>);

  @override
  _i5.Future<_i3.QueryResult<TParsed>> mutate<TParsed>(
    _i3.MutationOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mutate, [options]),
            returnValue: _i5.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_7<TParsed>(
                this,
                Invocation.method(#mutate, [options]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_7<TParsed>(
                    this,
                    Invocation.method(#mutate, [options]),
                  ),
                ),
          )
          as _i5.Future<_i3.QueryResult<TParsed>>);

  @override
  _i5.Stream<_i3.QueryResult<TParsed>> subscribe<TParsed>(
    _i3.SubscriptionOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [options]),
            returnValue: _i5.Stream<_i3.QueryResult<TParsed>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i3.QueryResult<TParsed>>.empty(),
          )
          as _i5.Stream<_i3.QueryResult<TParsed>>);

  @override
  _i5.Future<_i3.QueryResult<TParsed>> fetchMore<TParsed>(
    _i3.FetchMoreOptions? fetchMoreOptions, {
    required _i3.QueryOptions<TParsed>? originalOptions,
    required _i3.QueryResult<TParsed>? previousResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMore,
              [fetchMoreOptions],
              {
                #originalOptions: originalOptions,
                #previousResult: previousResult,
              },
            ),
            returnValue: _i5.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_7<TParsed>(
                this,
                Invocation.method(
                  #fetchMore,
                  [fetchMoreOptions],
                  {
                    #originalOptions: originalOptions,
                    #previousResult: previousResult,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_7<TParsed>(
                    this,
                    Invocation.method(
                      #fetchMore,
                      [fetchMoreOptions],
                      {
                        #originalOptions: originalOptions,
                        #previousResult: previousResult,
                      },
                    ),
                  ),
                ),
          )
          as _i5.Future<_i3.QueryResult<TParsed>>);

  @override
  Map<String, dynamic>? readQuery(
    _i3.Request? request, {
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readQuery, [request], {#optimistic: optimistic}),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  Map<String, dynamic>? readFragment(
    _i3.FragmentRequest? fragmentRequest, {
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readFragment,
              [fragmentRequest],
              {#optimistic: optimistic},
            ),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  void writeQuery(
    _i3.Request? request, {
    required Map<String, dynamic>? data,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeQuery,
      [request],
      {#data: data, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void writeFragment(
    _i3.FragmentRequest? fragmentRequest, {
    bool? broadcast = true,
    required Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeFragment,
      [fragmentRequest],
      {#broadcast: broadcast, #data: data},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i3.QueryResult<Object?>?>>? resetStore({
    bool? refetchQueries = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetStore, [], {
              #refetchQueries: refetchQueries,
            }),
            returnValueForMissingStub: null,
          )
          as _i5.Future<List<_i3.QueryResult<Object?>?>>?);
}
