// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type DeadLetterHistoryResult interface {
	IsDeadLetterHistoryResult()
}

type DeleteProjectDocumentResult interface {
	IsDeleteProjectDocumentResult()
}

type DeleteProjectSetupResult interface {
	IsDeleteProjectSetupResult()
}

type ExecutionHistoryResult interface {
	IsExecutionHistoryResult()
}

type ProjectDocumentPreviewResult interface {
	IsProjectDocumentPreviewResult()
}

type ProjectDocumentsResult interface {
	IsProjectDocumentsResult()
}

type ProjectRepositoryBranchesResult interface {
	IsProjectRepositoryBranchesResult()
}

type ProjectSetupResult interface {
	IsProjectSetupResult()
}

type ProjectSetupsResult interface {
	IsProjectSetupsResult()
}

type RequestProjectDocumentUploadResult interface {
	IsRequestProjectDocumentUploadResult()
}

type RequeueDeadLetterResult interface {
	IsRequeueDeadLetterResult()
}

type RunIngestionAgentResult interface {
	IsRunIngestionAgentResult()
}

type ScmSupportedOperationsResult interface {
	IsScmSupportedOperationsResult()
}

type SessionResult interface {
	IsSessionResult()
}

type SessionsResult interface {
	IsSessionsResult()
}

type StreamEventResult interface {
	IsStreamEventResult()
}

type TaskboardDeleteResult interface {
	IsTaskboardDeleteResult()
}

type TaskboardMutationResult interface {
	IsTaskboardMutationResult()
}

type TaskboardResult interface {
	IsTaskboardResult()
}

type TaskboardsResult interface {
	IsTaskboardsResult()
}

type UpsertProjectSetupResult interface {
	IsUpsertProjectSetupResult()
}

type WorkerSessionsResult interface {
	IsWorkerSessionsResult()
}

type WorkerSettingsResult interface {
	IsWorkerSettingsResult()
}

type WorkflowJobsResult interface {
	IsWorkflowJobsResult()
}

type CorrelationInput struct {
	RunID     *string `json:"runID,omitempty"`
	TaskID    *string `json:"taskID,omitempty"`
	JobID     *string `json:"jobID,omitempty"`
	ProjectID *string `json:"projectID,omitempty"`
}

type CreateTaskboardEpicInput struct {
	ProjectID        string   `json:"projectID"`
	BoardID          string   `json:"boardID"`
	Title            string   `json:"title"`
	Objective        *string  `json:"objective,omitempty"`
	State            string   `json:"state"`
	Rank             int32    `json:"rank"`
	DependsOnEpicIDs []string `json:"dependsOnEpicIDs,omitempty"`
}

type CreateTaskboardInput struct {
	ProjectID string `json:"projectID"`
	Name      string `json:"name"`
}

type CreateTaskboardTaskInput struct {
	ProjectID        string   `json:"projectID"`
	BoardID          string   `json:"boardID"`
	EpicID           string   `json:"epicID"`
	Title            string   `json:"title"`
	Description      *string  `json:"description,omitempty"`
	TaskType         string   `json:"taskType"`
	State            string   `json:"state"`
	Rank             int32    `json:"rank"`
	DependsOnTaskIDs []string `json:"dependsOnTaskIDs,omitempty"`
}

type DeadLetterHistoryRecord struct {
	Queue      string    `json:"queue"`
	TaskID     string    `json:"taskID"`
	JobKind    JobKind   `json:"jobKind"`
	Action     string    `json:"action"`
	LastError  *string   `json:"lastError,omitempty"`
	Reason     *string   `json:"reason,omitempty"`
	Actor      *string   `json:"actor,omitempty"`
	OccurredAt time.Time `json:"occurredAt"`
}

type DeadLetterHistorySuccess struct {
	Records []*DeadLetterHistoryRecord `json:"records"`
}

func (DeadLetterHistorySuccess) IsDeadLetterHistoryResult() {}

type DeleteProjectDocumentInput struct {
	ProjectID  string `json:"projectID"`
	DocumentID string `json:"documentID"`
}

type DeleteProjectDocumentSuccess struct {
	Ok bool `json:"ok"`
}

func (DeleteProjectDocumentSuccess) IsDeleteProjectDocumentResult() {}

type DeleteProjectSetupInput struct {
	ProjectID string `json:"projectID"`
}

type DeleteProjectSetupSuccess struct {
	Ok bool `json:"ok"`
}

func (DeleteProjectSetupSuccess) IsDeleteProjectSetupResult() {}

type DeleteTaskboardEpicInput struct {
	ProjectID string `json:"projectID"`
	BoardID   string `json:"boardID"`
	EpicID    string `json:"epicID"`
}

type DeleteTaskboardInput struct {
	ProjectID string `json:"projectID"`
	BoardID   string `json:"boardID"`
}

type DeleteTaskboardTaskInput struct {
	ProjectID string `json:"projectID"`
	BoardID   string `json:"boardID"`
	TaskID    string `json:"taskID"`
}

type ExecutionHistoryRecord struct {
	RunID          string    `json:"runID"`
	TaskID         string    `json:"taskID"`
	JobID          string    `json:"jobID"`
	ProjectID      string    `json:"projectID"`
	JobKind        JobKind   `json:"jobKind"`
	IdempotencyKey string    `json:"idempotencyKey"`
	Step           string    `json:"step"`
	Status         string    `json:"status"`
	ErrorMessage   *string   `json:"errorMessage,omitempty"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type ExecutionHistorySuccess struct {
	Records []*ExecutionHistoryRecord `json:"records"`
}

func (ExecutionHistorySuccess) IsExecutionHistoryResult() {}

type GraphError struct {
	Code    GraphErrorCode `json:"code"`
	Message string         `json:"message"`
	Field   *string        `json:"field,omitempty"`
}

func (GraphError) IsSessionsResult() {}

func (GraphError) IsSessionResult() {}

func (GraphError) IsWorkflowJobsResult() {}

func (GraphError) IsExecutionHistoryResult() {}

func (GraphError) IsDeadLetterHistoryResult() {}

func (GraphError) IsRequeueDeadLetterResult() {}

func (GraphError) IsTaskboardsResult() {}

func (GraphError) IsTaskboardResult() {}

func (GraphError) IsTaskboardMutationResult() {}

func (GraphError) IsTaskboardDeleteResult() {}

func (GraphError) IsProjectSetupsResult() {}

func (GraphError) IsProjectSetupResult() {}

func (GraphError) IsUpsertProjectSetupResult() {}

func (GraphError) IsDeleteProjectSetupResult() {}

func (GraphError) IsProjectDocumentsResult() {}

func (GraphError) IsProjectDocumentPreviewResult() {}

func (GraphError) IsRequestProjectDocumentUploadResult() {}

func (GraphError) IsRunIngestionAgentResult() {}

func (GraphError) IsProjectRepositoryBranchesResult() {}

func (GraphError) IsDeleteProjectDocumentResult() {}

func (GraphError) IsStreamEventResult() {}

func (GraphError) IsWorkerSessionsResult() {}

func (GraphError) IsWorkerSettingsResult() {}

func (GraphError) IsScmSupportedOperationsResult() {}

type Mutation struct {
}

type ProjectBoard struct {
	BoardID                  string            `json:"boardID"`
	TrackerProvider          TrackerSourceKind `json:"trackerProvider"`
	TaskboardName            *string           `json:"taskboardName,omitempty"`
	AppliesToAllRepositories bool              `json:"appliesToAllRepositories"`
	RepositoryIDs            []string          `json:"repositoryIDs"`
}

type ProjectBoardInput struct {
	TrackerProvider          TrackerSourceKind `json:"trackerProvider"`
	TaskboardName            *string           `json:"taskboardName,omitempty"`
	AppliesToAllRepositories bool              `json:"appliesToAllRepositories"`
	RepositoryIDs            []string          `json:"repositoryIDs,omitempty"`
}

type ProjectDocument struct {
	ProjectID   string    `json:"projectID"`
	DocumentID  string    `json:"documentID"`
	FileName    string    `json:"fileName"`
	ContentType string    `json:"contentType"`
	ObjectPath  string    `json:"objectPath"`
	CdnURL      string    `json:"cdnURL"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ProjectDocumentPreviewSuccess struct {
	Document *ProjectDocument `json:"document"`
}

func (ProjectDocumentPreviewSuccess) IsProjectDocumentPreviewResult() {}

type ProjectDocumentsSuccess struct {
	Documents []*ProjectDocument `json:"documents"`
}

func (ProjectDocumentsSuccess) IsProjectDocumentsResult() {}

type ProjectRepository struct {
	RepositoryID  string `json:"repositoryID"`
	ScmID         string `json:"scmID"`
	RepositoryURL string `json:"repositoryURL"`
	IsPrimary     bool   `json:"isPrimary"`
}

type ProjectRepositoryBranchOptions struct {
	RepositoryID  string   `json:"repositoryID"`
	RepositoryURL string   `json:"repositoryURL"`
	DefaultBranch *string  `json:"defaultBranch,omitempty"`
	Branches      []string `json:"branches"`
}

type ProjectRepositoryBranchesSuccess struct {
	Repositories []*ProjectRepositoryBranchOptions `json:"repositories"`
}

func (ProjectRepositoryBranchesSuccess) IsProjectRepositoryBranchesResult() {}

type ProjectRepositoryInput struct {
	RepositoryID  string `json:"repositoryID"`
	ScmID         string `json:"scmID"`
	RepositoryURL string `json:"repositoryURL"`
	IsPrimary     bool   `json:"isPrimary"`
}

type ProjectScm struct {
	ScmID       string      `json:"scmID"`
	ScmProvider SCMProvider `json:"scmProvider"`
}

type ProjectSCMInput struct {
	ScmID       string      `json:"scmID"`
	ScmProvider SCMProvider `json:"scmProvider"`
	ScmToken    string      `json:"scmToken"`
}

type ProjectSetup struct {
	ProjectID    string               `json:"projectID"`
	ProjectName  string               `json:"projectName"`
	Scms         []*ProjectScm        `json:"scms"`
	Repositories []*ProjectRepository `json:"repositories"`
	Boards       []*ProjectBoard      `json:"boards"`
	CreatedAt    time.Time            `json:"createdAt"`
	UpdatedAt    time.Time            `json:"updatedAt"`
}

type ProjectSetupSuccess struct {
	Project *ProjectSetup `json:"project"`
}

func (ProjectSetupSuccess) IsProjectSetupResult() {}

type ProjectSetupsSuccess struct {
	Projects []*ProjectSetup `json:"projects"`
}

func (ProjectSetupsSuccess) IsProjectSetupsResult() {}

type Query struct {
}

type RepositorySourceBranchInput struct {
	RepositoryID string `json:"repositoryID"`
	Branch       string `json:"branch"`
}

type RequestProjectDocumentUploadInput struct {
	ProjectID   string `json:"projectID"`
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType"`
}

type RequestProjectDocumentUploadSuccess struct {
	RequestID   string    `json:"requestID"`
	ProjectID   string    `json:"projectID"`
	DocumentID  string    `json:"documentID"`
	FileName    string    `json:"fileName"`
	ContentType string    `json:"contentType"`
	ObjectPath  string    `json:"objectPath"`
	UploadURL   string    `json:"uploadURL"`
	CdnURL      string    `json:"cdnURL"`
	ExpiresAt   time.Time `json:"expiresAt"`
	Status      string    `json:"status"`
}

func (RequestProjectDocumentUploadSuccess) IsRequestProjectDocumentUploadResult() {}

type RequeueDeadLetterInput struct {
	Queue  string `json:"queue"`
	TaskID string `json:"taskID"`
}

type RequeueDeadLetterSuccess struct {
	Ok bool `json:"ok"`
}

func (RequeueDeadLetterSuccess) IsRequeueDeadLetterResult() {}

type RunIngestionAgentInput struct {
	ProjectID                string                         `json:"projectID"`
	TaskboardName            string                         `json:"taskboardName"`
	SelectedDocumentIDs      []string                       `json:"selectedDocumentIDs,omitempty"`
	UserPrompt               *string                        `json:"userPrompt,omitempty"`
	RepositorySourceBranches []*RepositorySourceBranchInput `json:"repositorySourceBranches,omitempty"`
}

type RunIngestionAgentSuccess struct {
	RunID       string `json:"runID"`
	TaskID      string `json:"taskID"`
	JobID       string `json:"jobID"`
	QueueTaskID string `json:"queueTaskID"`
	Duplicate   bool   `json:"duplicate"`
}

func (RunIngestionAgentSuccess) IsRunIngestionAgentResult() {}

type ScmSupportedOperationsSuccess struct {
	Operations []SCMOperation `json:"operations"`
}

func (ScmSupportedOperationsSuccess) IsScmSupportedOperationsResult() {}

type SessionSuccess struct {
	Session *SessionSummary `json:"session"`
}

func (SessionSuccess) IsSessionResult() {}

type SessionSummary struct {
	RunID     string    `json:"runID"`
	TaskCount int32     `json:"taskCount"`
	JobCount  int32     `json:"jobCount"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type SessionsSuccess struct {
	Sessions []*SessionSummary `json:"sessions"`
}

func (SessionsSuccess) IsSessionsResult() {}

type StreamEvent struct {
	EventID       string            `json:"eventID"`
	StreamOffset  int32             `json:"streamOffset"`
	OccurredAt    time.Time         `json:"occurredAt"`
	RunID         *string           `json:"runID,omitempty"`
	TaskID        *string           `json:"taskID,omitempty"`
	JobID         *string           `json:"jobID,omitempty"`
	ProjectID     *string           `json:"projectID,omitempty"`
	SessionID     *string           `json:"sessionID,omitempty"`
	CorrelationID string            `json:"correlationID"`
	Source        StreamEventSource `json:"source"`
	EventType     string            `json:"eventType"`
	Payload       string            `json:"payload"`
}

type StreamEventSuccess struct {
	Event *StreamEvent `json:"event"`
}

func (StreamEventSuccess) IsStreamEventResult() {}

type Subscription struct {
}

type Taskboard struct {
	BoardID   string           `json:"boardID"`
	ProjectID string           `json:"projectID"`
	Name      string           `json:"name"`
	State     string           `json:"state"`
	Epics     []*TaskboardEpic `json:"epics"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

type TaskboardDeleteSuccess struct {
	Ok bool `json:"ok"`
}

func (TaskboardDeleteSuccess) IsTaskboardDeleteResult() {}

type TaskboardEpic struct {
	ID               string           `json:"id"`
	BoardID          string           `json:"boardID"`
	Title            string           `json:"title"`
	Objective        *string          `json:"objective,omitempty"`
	State            string           `json:"state"`
	Rank             int32            `json:"rank"`
	DependsOnEpicIDs []string         `json:"dependsOnEpicIDs"`
	Tasks            []*TaskboardTask `json:"tasks"`
}

type TaskboardMutationSuccess struct {
	Board *Taskboard `json:"board"`
}

func (TaskboardMutationSuccess) IsTaskboardMutationResult() {}

type TaskboardSuccess struct {
	Board *Taskboard `json:"board"`
}

func (TaskboardSuccess) IsTaskboardResult() {}

type TaskboardTask struct {
	ID               string   `json:"id"`
	BoardID          string   `json:"boardID"`
	EpicID           string   `json:"epicID"`
	Title            string   `json:"title"`
	Description      *string  `json:"description,omitempty"`
	TaskType         string   `json:"taskType"`
	State            string   `json:"state"`
	Rank             int32    `json:"rank"`
	DependsOnTaskIDs []string `json:"dependsOnTaskIDs"`
}

type TaskboardsSuccess struct {
	Boards []*Taskboard `json:"boards"`
}

func (TaskboardsSuccess) IsTaskboardsResult() {}

type UpdateTaskboardEpicInput struct {
	ProjectID        string   `json:"projectID"`
	BoardID          string   `json:"boardID"`
	EpicID           string   `json:"epicID"`
	Title            string   `json:"title"`
	Objective        *string  `json:"objective,omitempty"`
	State            string   `json:"state"`
	Rank             int32    `json:"rank"`
	DependsOnEpicIDs []string `json:"dependsOnEpicIDs,omitempty"`
}

type UpdateTaskboardInput struct {
	ProjectID string `json:"projectID"`
	BoardID   string `json:"boardID"`
	Name      string `json:"name"`
	State     string `json:"state"`
}

type UpdateTaskboardTaskInput struct {
	ProjectID        string   `json:"projectID"`
	BoardID          string   `json:"boardID"`
	TaskID           string   `json:"taskID"`
	EpicID           string   `json:"epicID"`
	Title            string   `json:"title"`
	Description      *string  `json:"description,omitempty"`
	TaskType         string   `json:"taskType"`
	State            string   `json:"state"`
	Rank             int32    `json:"rank"`
	DependsOnTaskIDs []string `json:"dependsOnTaskIDs,omitempty"`
}

type UpdateWorkerSettingsInput struct {
	HeartbeatIntervalSeconds int32 `json:"heartbeatIntervalSeconds"`
	ResponseDeadlineSeconds  int32 `json:"responseDeadlineSeconds"`
}

type UpsertProjectSetupInput struct {
	ProjectID    string                    `json:"projectID"`
	ProjectName  string                    `json:"projectName"`
	Scms         []*ProjectSCMInput        `json:"scms"`
	Repositories []*ProjectRepositoryInput `json:"repositories"`
	Boards       []*ProjectBoardInput      `json:"boards"`
}

type UpsertProjectSetupSuccess struct {
	Project *ProjectSetup `json:"project"`
}

func (UpsertProjectSetupSuccess) IsUpsertProjectSetupResult() {}

type WorkerSession struct {
	WorkerID       string    `json:"workerID"`
	Epoch          int32     `json:"epoch"`
	State          string    `json:"state"`
	LastHeartbeat  time.Time `json:"lastHeartbeat"`
	LeaseExpiresAt time.Time `json:"leaseExpiresAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type WorkerSessionsSuccess struct {
	Sessions []*WorkerSession `json:"sessions"`
}

func (WorkerSessionsSuccess) IsWorkerSessionsResult() {}

type WorkerSettings struct {
	HeartbeatIntervalSeconds int32     `json:"heartbeatIntervalSeconds"`
	ResponseDeadlineSeconds  int32     `json:"responseDeadlineSeconds"`
	UpdatedAt                time.Time `json:"updatedAt"`
}

type WorkerSettingsSuccess struct {
	Settings *WorkerSettings `json:"settings"`
}

func (WorkerSettingsSuccess) IsWorkerSettingsResult() {}

type WorkflowJob struct {
	RunID          string    `json:"runID"`
	TaskID         string    `json:"taskID"`
	JobID          string    `json:"jobID"`
	ProjectID      string    `json:"projectID"`
	JobKind        JobKind   `json:"jobKind"`
	IdempotencyKey string    `json:"idempotencyKey"`
	QueueTaskID    string    `json:"queueTaskID"`
	Queue          string    `json:"queue"`
	Status         string    `json:"status"`
	Duplicate      bool      `json:"duplicate"`
	EnqueuedAt     time.Time `json:"enqueuedAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type WorkflowJobsSuccess struct {
	Jobs []*WorkflowJob `json:"jobs"`
}

func (WorkflowJobsSuccess) IsWorkflowJobsResult() {}

type GraphErrorCode string

const (
	GraphErrorCodeInternal     GraphErrorCode = "INTERNAL"
	GraphErrorCodeValidation   GraphErrorCode = "VALIDATION"
	GraphErrorCodeConflict     GraphErrorCode = "CONFLICT"
	GraphErrorCodeNotFound     GraphErrorCode = "NOT_FOUND"
	GraphErrorCodeUnauthorized GraphErrorCode = "UNAUTHORIZED"
	GraphErrorCodeForbidden    GraphErrorCode = "FORBIDDEN"
	GraphErrorCodeUnavailable  GraphErrorCode = "UNAVAILABLE"
)

var AllGraphErrorCode = []GraphErrorCode{
	GraphErrorCodeInternal,
	GraphErrorCodeValidation,
	GraphErrorCodeConflict,
	GraphErrorCodeNotFound,
	GraphErrorCodeUnauthorized,
	GraphErrorCodeForbidden,
	GraphErrorCodeUnavailable,
}

func (e GraphErrorCode) IsValid() bool {
	switch e {
	case GraphErrorCodeInternal, GraphErrorCodeValidation, GraphErrorCodeConflict, GraphErrorCodeNotFound, GraphErrorCodeUnauthorized, GraphErrorCodeForbidden, GraphErrorCodeUnavailable:
		return true
	}
	return false
}

func (e GraphErrorCode) String() string {
	return string(e)
}

func (e *GraphErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GraphErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GraphErrorCode", str)
	}
	return nil
}

func (e GraphErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GraphErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GraphErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobKind string

const (
	JobKindIngestionAgentRun            JobKind = "INGESTION_AGENT_RUN"
	JobKindAgentWorkflowRun             JobKind = "AGENT_WORKFLOW_RUN"
	JobKindScmWorkflowRun               JobKind = "SCM_WORKFLOW_RUN"
	JobKindProjectDocumentUploadPrepare JobKind = "PROJECT_DOCUMENT_UPLOAD_PREPARE"
	JobKindProjectDocumentDelete        JobKind = "PROJECT_DOCUMENT_DELETE"
)

var AllJobKind = []JobKind{
	JobKindIngestionAgentRun,
	JobKindAgentWorkflowRun,
	JobKindScmWorkflowRun,
	JobKindProjectDocumentUploadPrepare,
	JobKindProjectDocumentDelete,
}

func (e JobKind) IsValid() bool {
	switch e {
	case JobKindIngestionAgentRun, JobKindAgentWorkflowRun, JobKindScmWorkflowRun, JobKindProjectDocumentUploadPrepare, JobKindProjectDocumentDelete:
		return true
	}
	return false
}

func (e JobKind) String() string {
	return string(e)
}

func (e *JobKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobKind", str)
	}
	return nil
}

func (e JobKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SCMMergeMethod string

const (
	SCMMergeMethodMerge  SCMMergeMethod = "MERGE"
	SCMMergeMethodSquash SCMMergeMethod = "SQUASH"
	SCMMergeMethodRebase SCMMergeMethod = "REBASE"
)

var AllSCMMergeMethod = []SCMMergeMethod{
	SCMMergeMethodMerge,
	SCMMergeMethodSquash,
	SCMMergeMethodRebase,
}

func (e SCMMergeMethod) IsValid() bool {
	switch e {
	case SCMMergeMethodMerge, SCMMergeMethodSquash, SCMMergeMethodRebase:
		return true
	}
	return false
}

func (e SCMMergeMethod) String() string {
	return string(e)
}

func (e *SCMMergeMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SCMMergeMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SCMMergeMethod", str)
	}
	return nil
}

func (e SCMMergeMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SCMMergeMethod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SCMMergeMethod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SCMOperation string

const (
	SCMOperationSourceState         SCMOperation = "SOURCE_STATE"
	SCMOperationEnsureRepository    SCMOperation = "ENSURE_REPOSITORY"
	SCMOperationSyncRepository      SCMOperation = "SYNC_REPOSITORY"
	SCMOperationCleanupRepository   SCMOperation = "CLEANUP_REPOSITORY"
	SCMOperationEnsureBranch        SCMOperation = "ENSURE_BRANCH"
	SCMOperationSyncBranch          SCMOperation = "SYNC_BRANCH"
	SCMOperationUpsertPullRequest   SCMOperation = "UPSERT_PULL_REQUEST"
	SCMOperationGetPullRequest      SCMOperation = "GET_PULL_REQUEST"
	SCMOperationSubmitReview        SCMOperation = "SUBMIT_REVIEW"
	SCMOperationCheckMergeReadiness SCMOperation = "CHECK_MERGE_READINESS"
	SCMOperationMergePullRequest    SCMOperation = "MERGE_PULL_REQUEST"
)

var AllSCMOperation = []SCMOperation{
	SCMOperationSourceState,
	SCMOperationEnsureRepository,
	SCMOperationSyncRepository,
	SCMOperationCleanupRepository,
	SCMOperationEnsureBranch,
	SCMOperationSyncBranch,
	SCMOperationUpsertPullRequest,
	SCMOperationGetPullRequest,
	SCMOperationSubmitReview,
	SCMOperationCheckMergeReadiness,
	SCMOperationMergePullRequest,
}

func (e SCMOperation) IsValid() bool {
	switch e {
	case SCMOperationSourceState, SCMOperationEnsureRepository, SCMOperationSyncRepository, SCMOperationCleanupRepository, SCMOperationEnsureBranch, SCMOperationSyncBranch, SCMOperationUpsertPullRequest, SCMOperationGetPullRequest, SCMOperationSubmitReview, SCMOperationCheckMergeReadiness, SCMOperationMergePullRequest:
		return true
	}
	return false
}

func (e SCMOperation) String() string {
	return string(e)
}

func (e *SCMOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SCMOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SCMOperation", str)
	}
	return nil
}

func (e SCMOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SCMOperation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SCMOperation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SCMProvider string

const (
	SCMProviderGithub SCMProvider = "GITHUB"
)

var AllSCMProvider = []SCMProvider{
	SCMProviderGithub,
}

func (e SCMProvider) IsValid() bool {
	switch e {
	case SCMProviderGithub:
		return true
	}
	return false
}

func (e SCMProvider) String() string {
	return string(e)
}

func (e *SCMProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SCMProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SCMProvider", str)
	}
	return nil
}

func (e SCMProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SCMProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SCMProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SCMReviewDecision string

const (
	SCMReviewDecisionApprove        SCMReviewDecision = "APPROVE"
	SCMReviewDecisionRequestChanges SCMReviewDecision = "REQUEST_CHANGES"
	SCMReviewDecisionComment        SCMReviewDecision = "COMMENT"
)

var AllSCMReviewDecision = []SCMReviewDecision{
	SCMReviewDecisionApprove,
	SCMReviewDecisionRequestChanges,
	SCMReviewDecisionComment,
}

func (e SCMReviewDecision) IsValid() bool {
	switch e {
	case SCMReviewDecisionApprove, SCMReviewDecisionRequestChanges, SCMReviewDecisionComment:
		return true
	}
	return false
}

func (e SCMReviewDecision) String() string {
	return string(e)
}

func (e *SCMReviewDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SCMReviewDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SCMReviewDecision", str)
	}
	return nil
}

func (e SCMReviewDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SCMReviewDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SCMReviewDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StreamEventSource string

const (
	StreamEventSourceAcp         StreamEventSource = "ACP"
	StreamEventSourceSessionFile StreamEventSource = "SESSION_FILE"
	StreamEventSourceWorker      StreamEventSource = "WORKER"
)

var AllStreamEventSource = []StreamEventSource{
	StreamEventSourceAcp,
	StreamEventSourceSessionFile,
	StreamEventSourceWorker,
}

func (e StreamEventSource) IsValid() bool {
	switch e {
	case StreamEventSourceAcp, StreamEventSourceSessionFile, StreamEventSourceWorker:
		return true
	}
	return false
}

func (e StreamEventSource) String() string {
	return string(e)
}

func (e *StreamEventSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StreamEventSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StreamEventSource", str)
	}
	return nil
}

func (e StreamEventSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StreamEventSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StreamEventSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrackerSourceKind string

const (
	TrackerSourceKindInternal TrackerSourceKind = "INTERNAL"
)

var AllTrackerSourceKind = []TrackerSourceKind{
	TrackerSourceKindInternal,
}

func (e TrackerSourceKind) IsValid() bool {
	switch e {
	case TrackerSourceKindInternal:
		return true
	}
	return false
}

func (e TrackerSourceKind) String() string {
	return string(e)
}

func (e *TrackerSourceKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrackerSourceKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrackerSourceKind", str)
	}
	return nil
}

func (e TrackerSourceKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrackerSourceKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrackerSourceKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
