// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type EnqueueSCMWorkflowInput struct {
	Operation         string  `json:"operation"`
	Provider          string  `json:"provider"`
	Owner             string  `json:"owner"`
	Repository        string  `json:"repository"`
	RunID             string  `json:"runID"`
	TaskID            string  `json:"taskID"`
	JobID             string  `json:"jobID"`
	IdempotencyKey    string  `json:"idempotencyKey"`
	WorktreePath      *string `json:"worktreePath,omitempty"`
	BaseBranch        *string `json:"baseBranch,omitempty"`
	TargetBranch      *string `json:"targetBranch,omitempty"`
	PullRequestNumber *int32  `json:"pullRequestNumber,omitempty"`
	PullRequestTitle  *string `json:"pullRequestTitle,omitempty"`
	PullRequestBody   *string `json:"pullRequestBody,omitempty"`
	ReviewDecision    *string `json:"reviewDecision,omitempty"`
	ReviewBody        *string `json:"reviewBody,omitempty"`
}

type EnqueueSCMWorkflowResult struct {
	QueueTaskID string `json:"queueTaskID"`
	Duplicate   bool   `json:"duplicate"`
}

type Mutation struct {
}

type Query struct {
}
