package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	applicationcontrolplane "agentic-orchestrator/internal/application/controlplane"
	domainrealtime "agentic-orchestrator/internal/domain/realtime"
	domainstream "agentic-orchestrator/internal/domain/stream"
	"agentic-orchestrator/internal/interface/graphql/models"
	"context"
	"fmt"
	"time"
)

// ApproveIssueIntake is the resolver for the approveIssueIntake field.
func (r *mutationResolver) ApproveIssueIntake(ctx context.Context, input models.ApproveIssueIntakeInput) (models.ApproveIssueIntakeResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	decision, err := r.Resolver.ControlPlaneService.ApproveIssueIntake(ctx, applicationcontrolplane.ApproveIssueIntakeRequest{
		RunID:          input.RunID,
		TaskID:         input.TaskID,
		JobID:          input.JobID,
		ProjectID:      input.ProjectID,
		Source:         input.Source,
		IssueReference: input.IssueReference,
		ApprovedBy:     input.ApprovedBy,
	})
	if err != nil {
		return graphErrorFromError(fmt.Errorf("approve issue intake: %w", err)), nil
	}
	return models.ApproveIssueIntakeSuccess{Decision: mapSupervisorDecision(decision)}, nil
}

// RequeueDeadLetter is the resolver for the requeueDeadLetter field.
func (r *mutationResolver) RequeueDeadLetter(ctx context.Context, input models.RequeueDeadLetterInput) (models.RequeueDeadLetterResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	if err := r.Resolver.ControlPlaneService.RequeueDeadLetter(ctx, input.Queue, input.TaskID); err != nil {
		return graphErrorFromError(err), nil
	}
	return models.RequeueDeadLetterSuccess{Ok: true}, nil
}

// UpsertProjectSetup is the resolver for the upsertProjectSetup field.
func (r *mutationResolver) UpsertProjectSetup(ctx context.Context, input models.UpsertProjectSetupInput) (models.UpsertProjectSetupResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	repositories := make([]applicationcontrolplane.ProjectRepository, 0, len(input.Repositories))
	for _, repository := range input.Repositories {
		repositories = append(repositories, applicationcontrolplane.ProjectRepository{
			RepositoryID:  repository.RepositoryID,
			SCMID:         repository.ScmID,
			RepositoryURL: repository.RepositoryURL,
			IsPrimary:     repository.IsPrimary,
		})
	}
	scms := make([]applicationcontrolplane.ProjectSCM, 0, len(input.Scms))
	for _, scm := range input.Scms {
		scms = append(scms, applicationcontrolplane.ProjectSCM{
			SCMID:       scm.ScmID,
			SCMProvider: toSCMProviderString(scm.ScmProvider),
			SCMToken:    scm.ScmToken,
		})
	}
	boards := make([]applicationcontrolplane.ProjectBoard, 0, len(input.Boards))
	for _, board := range input.Boards {
		repositoryIDs := make([]string, 0, len(board.RepositoryIDs))
		for _, repositoryID := range board.RepositoryIDs {
			repositoryIDs = append(repositoryIDs, repositoryID)
		}
		boards = append(boards, applicationcontrolplane.ProjectBoard{
			TrackerProvider:          toTrackerSourceKindString(board.TrackerProvider),
			TaskboardName:            derefString(board.TaskboardName),
			AppliesToAllRepositories: board.AppliesToAllRepositories,
			RepositoryIDs:            repositoryIDs,
		})
	}
	setup, err := r.Resolver.ControlPlaneService.UpsertProjectSetup(ctx, applicationcontrolplane.UpsertProjectSetupRequest{
		ProjectID:    input.ProjectID,
		ProjectName:  input.ProjectName,
		SCMs:         scms,
		Repositories: repositories,
		Boards:       boards,
	})
	if err != nil {
		return graphErrorFromError(fmt.Errorf("upsert project setup: %w", err)), nil
	}
	mapped, mapErr := toGraphProjectSetup(setup)
	if mapErr != nil {
		return graphErrorFromError(mapErr), nil
	}
	return models.UpsertProjectSetupSuccess{Project: mapped}, nil
}

// DeleteProjectSetup is the resolver for the deleteProjectSetup field.
func (r *mutationResolver) DeleteProjectSetup(ctx context.Context, input models.DeleteProjectSetupInput) (models.DeleteProjectSetupResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	if err := r.Resolver.ControlPlaneService.DeleteProjectSetup(ctx, input.ProjectID); err != nil {
		return graphErrorFromError(fmt.Errorf("delete project setup: %w", err)), nil
	}
	return models.DeleteProjectSetupSuccess{Ok: true}, nil
}

// RequestProjectDocumentUpload is the resolver for the requestProjectDocumentUpload field.
func (r *mutationResolver) RequestProjectDocumentUpload(ctx context.Context, input models.RequestProjectDocumentUploadInput) (models.RequestProjectDocumentUploadResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	result, err := r.Resolver.ControlPlaneService.RequestProjectDocumentUpload(ctx, applicationcontrolplane.RequestProjectDocumentUploadInput{
		ProjectID:   input.ProjectID,
		FileName:    input.FileName,
		ContentType: input.ContentType,
	})
	if err != nil {
		return graphErrorFromError(fmt.Errorf("request project document upload: %w", err)), nil
	}
	return models.RequestProjectDocumentUploadSuccess{
		RequestID:   result.RequestID,
		ProjectID:   result.ProjectID,
		DocumentID:  result.DocumentID,
		FileName:    result.FileName,
		ContentType: result.ContentType,
		ObjectPath:  result.ObjectPath,
		UploadURL:   result.UploadURL,
		CdnURL:      result.CDNURL,
		ExpiresAt:   result.ExpiresAt.UTC(),
		Status:      result.Status,
	}, nil
}

// RunIngestionAgent is the resolver for the runIngestionAgent field.
func (r *mutationResolver) RunIngestionAgent(ctx context.Context, input models.RunIngestionAgentInput) (models.RunIngestionAgentResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	result, err := r.Resolver.ControlPlaneService.RunIngestionAgent(ctx, applicationcontrolplane.RunIngestionAgentInput{
		ProjectID:                input.ProjectID,
		BoardID:                  derefString(input.BoardID),
		SelectedDocumentIDs:      input.SelectedDocumentIDs,
		UserPrompt:               derefString(input.UserPrompt),
		RepositorySourceBranches: mapRepositorySourceBranches(input.RepositorySourceBranches),
	})
	if err != nil {
		return graphErrorFromError(fmt.Errorf("run ingestion agent: %w", err)), nil
	}
	return models.RunIngestionAgentSuccess{
		RunID:       result.RunID,
		TaskID:      result.TaskID,
		JobID:       result.JobID,
		QueueTaskID: result.QueueTaskID,
		Duplicate:   result.Duplicate,
	}, nil
}

// DeleteProjectDocument is the resolver for the deleteProjectDocument field.
func (r *mutationResolver) DeleteProjectDocument(ctx context.Context, input models.DeleteProjectDocumentInput) (models.DeleteProjectDocumentResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	if err := r.Resolver.ControlPlaneService.DeleteProjectDocument(ctx, input.ProjectID, input.DocumentID); err != nil {
		return graphErrorFromError(fmt.Errorf("delete project document: %w", err)), nil
	}
	return models.DeleteProjectDocumentSuccess{Ok: true}, nil
}

// UpdateWorkerSettings is the resolver for the updateWorkerSettings field.
func (r *mutationResolver) UpdateWorkerSettings(ctx context.Context, input models.UpdateWorkerSettingsInput) (models.WorkerSettingsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.WorkerService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "worker service is not configured"}, nil
	}
	settings, err := r.Resolver.WorkerService.UpdateSettings(ctx, domainrealtime.Settings{
		HeartbeatInterval: time.Duration(input.HeartbeatIntervalSeconds) * time.Second,
		ResponseDeadline:  time.Duration(input.ResponseDeadlineSeconds) * time.Second,
		UpdatedAt:         time.Now().UTC(),
	})
	if err != nil {
		return graphErrorFromError(fmt.Errorf("update worker settings: %w", err)), nil
	}
	return models.WorkerSettingsSuccess{Settings: &models.WorkerSettings{HeartbeatIntervalSeconds: int32(settings.HeartbeatInterval.Seconds()), ResponseDeadlineSeconds: int32(settings.ResponseDeadline.Seconds()), UpdatedAt: settings.UpdatedAt.UTC()}}, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, limit *int32) (models.SessionsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	summaries, err := r.Resolver.ControlPlaneService.Sessions(ctx, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load sessions: %w", err)), nil
	}
	items := make([]*models.SessionSummary, 0, len(summaries))
	for _, item := range summaries {
		items = append(items, &models.SessionSummary{RunID: item.RunID, TaskCount: int32(item.TaskCount), JobCount: int32(item.JobCount), UpdatedAt: item.UpdatedAt.UTC()})
	}
	return models.SessionsSuccess{Sessions: items}, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, runID string) (models.SessionResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	summary, err := r.Resolver.ControlPlaneService.Session(ctx, runID)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load session: %w", err)), nil
	}
	if summary == nil {
		return models.GraphError{Code: models.GraphErrorCodeNotFound, Message: "session not found", Field: strPtr("runID")}, nil
	}
	return models.SessionSuccess{Session: &models.SessionSummary{RunID: summary.RunID, TaskCount: int32(summary.TaskCount), JobCount: int32(summary.JobCount), UpdatedAt: summary.UpdatedAt.UTC()}}, nil
}

// WorkflowJobs is the resolver for the workflowJobs field.
func (r *queryResolver) WorkflowJobs(ctx context.Context, runID string, taskID *string, limit *int32) (models.WorkflowJobsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	jobs, err := r.Resolver.ControlPlaneService.WorkflowJobs(ctx, runID, derefString(taskID), int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load workflow jobs: %w", err)), nil
	}
	items := make([]*models.WorkflowJob, 0, len(jobs))
	for _, item := range jobs {
		mappedJobKind, mapErr := toGraphJobKind(item.JobKind)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, &models.WorkflowJob{
			RunID:          item.RunID,
			TaskID:         item.TaskID,
			JobID:          item.JobID,
			ProjectID:      item.ProjectID,
			JobKind:        mappedJobKind,
			IdempotencyKey: item.IdempotencyKey,
			QueueTaskID:    item.QueueTaskID,
			Queue:          item.Queue,
			Status:         item.Status,
			Duplicate:      item.Duplicate,
			EnqueuedAt:     item.EnqueuedAt.UTC(),
			UpdatedAt:      item.UpdatedAt.UTC(),
		})
	}
	return models.WorkflowJobsSuccess{Jobs: items}, nil
}

// ExecutionHistory is the resolver for the executionHistory field.
func (r *queryResolver) ExecutionHistory(ctx context.Context, correlation models.SupervisorCorrelationInput, limit *int32) (models.ExecutionHistoryResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	history, err := r.Resolver.ControlPlaneService.ExecutionHistory(ctx, applicationcontrolplane.CorrelationFilter{RunID: correlation.RunID, TaskID: correlation.TaskID, JobID: correlation.JobID, ProjectID: derefString(correlation.ProjectID)}, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load execution history: %w", err)), nil
	}
	items := make([]*models.ExecutionHistoryRecord, 0, len(history))
	for _, item := range history {
		mappedJobKind, mapErr := toGraphJobKind(item.JobKind)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, &models.ExecutionHistoryRecord{
			RunID:          item.RunID,
			TaskID:         item.TaskID,
			JobID:          item.JobID,
			ProjectID:      item.ProjectID,
			JobKind:        mappedJobKind,
			IdempotencyKey: item.IdempotencyKey,
			Step:           item.Step,
			Status:         string(item.Status),
			ErrorMessage:   nilIfEmpty(item.ErrorMessage),
			UpdatedAt:      item.UpdatedAt.UTC(),
		})
	}
	return models.ExecutionHistorySuccess{Records: items}, nil
}

// DeadLetterHistory is the resolver for the deadLetterHistory field.
func (r *queryResolver) DeadLetterHistory(ctx context.Context, queue *string, limit *int32) (models.DeadLetterHistoryResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	history, err := r.Resolver.ControlPlaneService.DeadLetterHistory(ctx, derefString(queue), int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load dead-letter history: %w", err)), nil
	}
	items := make([]*models.DeadLetterHistoryRecord, 0, len(history))
	for _, item := range history {
		mappedJobKind, mapErr := toGraphJobKind(item.JobKind)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, &models.DeadLetterHistoryRecord{
			Queue:      item.Queue,
			TaskID:     item.TaskID,
			JobKind:    mappedJobKind,
			Action:     string(item.Action),
			LastError:  nilIfEmpty(item.LastError),
			Reason:     nilIfEmpty(item.Reason),
			Actor:      nilIfEmpty(item.Actor),
			OccurredAt: item.OccurredAt.UTC(),
		})
	}
	return models.DeadLetterHistorySuccess{Records: items}, nil
}

// ProjectSetups is the resolver for the projectSetups field.
func (r *queryResolver) ProjectSetups(ctx context.Context, limit *int32) (models.ProjectSetupsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	projects, err := r.Resolver.ControlPlaneService.ProjectSetups(ctx, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load project setups: %w", err)), nil
	}
	items := make([]*models.ProjectSetup, 0, len(projects))
	for _, project := range projects {
		mapped, mapErr := toGraphProjectSetup(&project)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, mapped)
	}
	return models.ProjectSetupsSuccess{Projects: items}, nil
}

// ProjectSetup is the resolver for the projectSetup field.
func (r *queryResolver) ProjectSetup(ctx context.Context, projectID string) (models.ProjectSetupResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	project, err := r.Resolver.ControlPlaneService.ProjectSetup(ctx, projectID)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load project setup: %w", err)), nil
	}
	if project == nil {
		return models.GraphError{Code: models.GraphErrorCodeNotFound, Message: "project setup not found", Field: strPtr("projectID")}, nil
	}
	mapped, mapErr := toGraphProjectSetup(project)
	if mapErr != nil {
		return graphErrorFromError(mapErr), nil
	}
	return models.ProjectSetupSuccess{Project: mapped}, nil
}

// ProjectDocuments is the resolver for the projectDocuments field.
func (r *queryResolver) ProjectDocuments(ctx context.Context, projectID string, limit *int32) (models.ProjectDocumentsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	documents, err := r.Resolver.ControlPlaneService.ProjectDocuments(ctx, projectID, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load project documents: %w", err)), nil
	}
	items := make([]*models.ProjectDocument, 0, len(documents))
	for _, document := range documents {
		items = append(items, toGraphProjectDocument(document))
	}
	return models.ProjectDocumentsSuccess{Documents: items}, nil
}

// ProjectDocumentPreview is the resolver for the projectDocumentPreview field.
func (r *queryResolver) ProjectDocumentPreview(ctx context.Context, projectID string, documentID string) (models.ProjectDocumentPreviewResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	preview, err := r.Resolver.ControlPlaneService.ProjectDocumentPreview(ctx, projectID, documentID)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load project document preview: %w", err)), nil
	}
	if preview == nil {
		return models.GraphError{Code: models.GraphErrorCodeNotFound, Message: "project document not found", Field: strPtr("documentID")}, nil
	}
	return models.ProjectDocumentPreviewSuccess{Document: &models.ProjectDocument{
		ProjectID:   preview.ProjectID,
		DocumentID:  preview.DocumentID,
		FileName:    preview.FileName,
		ContentType: preview.ContentType,
		ObjectPath:  preview.ObjectPath,
		CdnURL:      preview.CDNURL,
		Status:      preview.Status,
		CreatedAt:   preview.CreatedAt.UTC(),
		UpdatedAt:   preview.UpdatedAt.UTC(),
	}}, nil
}

// ProjectRepositoryBranches is the resolver for the projectRepositoryBranches field.
func (r *queryResolver) ProjectRepositoryBranches(ctx context.Context, projectID string) (models.ProjectRepositoryBranchesResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	repositories, err := r.Resolver.ControlPlaneService.ProjectRepositoryBranches(ctx, projectID)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load project repository branches: %w", err)), nil
	}
	items := make([]*models.ProjectRepositoryBranchOptions, 0, len(repositories))
	for _, repository := range repositories {
		items = append(items, &models.ProjectRepositoryBranchOptions{
			RepositoryID:  repository.RepositoryID,
			RepositoryURL: repository.RepositoryURL,
			DefaultBranch: nilIfEmpty(repository.DefaultBranch),
			Branches:      repository.Branches,
		})
	}
	return models.ProjectRepositoryBranchesSuccess{Repositories: items}, nil
}

// WorkerSessions is the resolver for the workerSessions field.
func (r *queryResolver) WorkerSessions(ctx context.Context, limit *int32) (models.WorkerSessionsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.WorkerService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "worker service is not configured"}, nil
	}
	workers, err := r.Resolver.WorkerService.ListWorkers(ctx, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load worker sessions: %w", err)), nil
	}
	sessions := make([]*models.WorkerSession, 0, len(workers))
	for _, worker := range workers {
		sessions = append(sessions, &models.WorkerSession{WorkerID: worker.WorkerID, Epoch: int32(worker.Epoch), State: string(worker.State), LastHeartbeat: worker.LastHeartbeat.UTC(), LeaseExpiresAt: worker.LeaseExpiresAt.UTC(), UpdatedAt: worker.UpdatedAt.UTC()})
	}
	return models.WorkerSessionsSuccess{Sessions: sessions}, nil
}

// WorkerSettings is the resolver for the workerSettings field.
func (r *queryResolver) WorkerSettings(ctx context.Context) (models.WorkerSettingsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.WorkerService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "worker service is not configured"}, nil
	}
	settings, err := r.Resolver.WorkerService.GetSettings(ctx)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load worker settings: %w", err)), nil
	}
	return models.WorkerSettingsSuccess{Settings: &models.WorkerSettings{HeartbeatIntervalSeconds: int32(settings.HeartbeatInterval.Seconds()), ResponseDeadlineSeconds: int32(settings.ResponseDeadline.Seconds()), UpdatedAt: settings.UpdatedAt.UTC()}}, nil
}

// WorkerSessionStream is the resolver for the workerSessionStream field.
func (r *subscriptionResolver) WorkerSessionStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventWorkerRegistrationAccepted, domainstream.EventWorkerHeartbeat, domainstream.EventWorkerInvalidated:
			return true
		default:
			return false
		}
	})
}

// SessionActivityStream is the resolver for the sessionActivityStream field.
func (r *subscriptionResolver) SessionActivityStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventSessionStarted, domainstream.EventSessionUpdated, domainstream.EventSessionCheckpointed, domainstream.EventSessionEnded, domainstream.EventSessionRecovered, domainstream.EventSessionHealth, domainstream.EventSessionInjectedPrompt:
			return true
		default:
			return false
		}
	})
}

// WorkflowExecutionStream is the resolver for the workflowExecutionStream field.
func (r *subscriptionResolver) WorkflowExecutionStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventToolStarted, domainstream.EventToolCompleted, domainstream.EventPermissionRequested, domainstream.EventPermissionDecided:
			return true
		default:
			return false
		}
	})
}

// AgentOutputStream is the resolver for the agentOutputStream field.
func (r *subscriptionResolver) AgentOutputStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventAgentChunk, domainstream.EventAgentTurnCompleted:
			return true
		default:
			return false
		}
	})
}
