package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	applicationcontrolplane "agentic-orchestrator/internal/application/controlplane"
	applicationstream "agentic-orchestrator/internal/application/stream"
	"agentic-orchestrator/internal/application/taskengine"
	domainstream "agentic-orchestrator/internal/domain/stream"
	"agentic-orchestrator/internal/interface/graphql/models"
	"context"
	"encoding/json"
	"fmt"
	"math"
	"strings"
)

// EnqueueIngestionWorkflow is the resolver for the enqueueIngestionWorkflow field.
func (r *mutationResolver) EnqueueIngestionWorkflow(ctx context.Context, input models.EnqueueIngestionWorkflowInput) (models.EnqueueIngestionWorkflowResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	if input.BoardSource == nil {
		return models.GraphError{Code: models.GraphErrorCodeValidation, Message: "boardSource is required", Field: strPtr("boardSource")}, nil
	}
	request := applicationcontrolplane.EnqueueIngestionWorkflowRequest{
		RunID:          input.RunID,
		TaskID:         input.TaskID,
		JobID:          input.JobID,
		IdempotencyKey: input.IdempotencyKey,
		Prompt:         input.Prompt,
		ProjectID:      input.ProjectID,
		WorkflowID:     input.WorkflowID,
		BoardSource: applicationcontrolplane.IngestionBoardSource{
			Kind:     toTrackerSourceKindString(input.BoardSource.Kind),
			Location: derefString(input.BoardSource.Location),
			BoardID:  derefString(input.BoardSource.BoardID),
			Config:   map[string]any{},
		},
	}
	result, err := r.Resolver.ControlPlaneService.EnqueueIngestionWorkflow(ctx, request)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("enqueue ingestion workflow: %w", err)), nil
	}
	return models.EnqueueIngestionWorkflowSuccess{QueueTaskID: result.QueueTaskID, Duplicate: result.Duplicate}, nil
}

// ApproveIssueIntake is the resolver for the approveIssueIntake field.
func (r *mutationResolver) ApproveIssueIntake(ctx context.Context, input models.ApproveIssueIntakeInput) (models.ApproveIssueIntakeResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	decision, err := r.Resolver.ControlPlaneService.ApproveIssueIntake(ctx, applicationcontrolplane.ApproveIssueIntakeRequest{
		RunID:          input.RunID,
		TaskID:         input.TaskID,
		JobID:          input.JobID,
		Source:         input.Source,
		IssueReference: input.IssueReference,
		ApprovedBy:     input.ApprovedBy,
	})
	if err != nil {
		return graphErrorFromError(fmt.Errorf("approve issue intake: %w", err)), nil
	}
	return models.ApproveIssueIntakeSuccess{Decision: mapSupervisorDecision(decision)}, nil
}

// RequeueDeadLetter is the resolver for the requeueDeadLetter field.
func (r *mutationResolver) RequeueDeadLetter(ctx context.Context, input models.RequeueDeadLetterInput) (models.RequeueDeadLetterResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	if err := r.Resolver.ControlPlaneService.RequeueDeadLetter(ctx, input.Queue, input.TaskID); err != nil {
		return graphErrorFromError(err), nil
	}
	return models.RequeueDeadLetterSuccess{Ok: true}, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, limit *int32) (models.SessionsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	summaries, err := r.Resolver.ControlPlaneService.Sessions(ctx, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load sessions: %w", err)), nil
	}
	items := make([]*models.SessionSummary, 0, len(summaries))
	for _, item := range summaries {
		items = append(items, &models.SessionSummary{RunID: item.RunID, TaskCount: int32(item.TaskCount), JobCount: int32(item.JobCount), UpdatedAt: item.UpdatedAt.UTC()})
	}
	return models.SessionsSuccess{Sessions: items}, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, runID string) (models.SessionResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	summary, err := r.Resolver.ControlPlaneService.Session(ctx, runID)
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load session: %w", err)), nil
	}
	if summary == nil {
		return models.GraphError{Code: models.GraphErrorCodeNotFound, Message: "session not found", Field: strPtr("runID")}, nil
	}
	return models.SessionSuccess{Session: &models.SessionSummary{RunID: summary.RunID, TaskCount: int32(summary.TaskCount), JobCount: int32(summary.JobCount), UpdatedAt: summary.UpdatedAt.UTC()}}, nil
}

// Workers is the resolver for the workers field.
func (r *queryResolver) Workers(ctx context.Context, limit *int32) (models.WorkersResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	workers, err := r.Resolver.ControlPlaneService.Workers(ctx, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load workers: %w", err)), nil
	}
	items := make([]*models.WorkerSummary, 0, len(workers))
	for _, item := range workers {
		capabilities := make([]models.JobKind, 0, len(item.Capabilities))
		for _, capability := range item.Capabilities {
			mappedCapability, mapErr := toGraphJobKind(capability)
			if mapErr != nil {
				return graphErrorFromError(mapErr), nil
			}
			capabilities = append(capabilities, mappedCapability)
		}
		items = append(items, &models.WorkerSummary{WorkerID: item.WorkerID, Capabilities: capabilities, LastHeartbeat: item.LastHeartbeat.UTC()})
	}
	return models.WorkersSuccess{Workers: items}, nil
}

// WorkflowJobs is the resolver for the workflowJobs field.
func (r *queryResolver) WorkflowJobs(ctx context.Context, runID string, taskID *string, limit *int32) (models.WorkflowJobsResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	jobs, err := r.Resolver.ControlPlaneService.WorkflowJobs(ctx, runID, derefString(taskID), int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load workflow jobs: %w", err)), nil
	}
	items := make([]*models.WorkflowJob, 0, len(jobs))
	for _, item := range jobs {
		mappedJobKind, mapErr := toGraphJobKind(item.JobKind)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, &models.WorkflowJob{
			RunID:          item.RunID,
			TaskID:         item.TaskID,
			JobID:          item.JobID,
			JobKind:        mappedJobKind,
			IdempotencyKey: item.IdempotencyKey,
			QueueTaskID:    item.QueueTaskID,
			Queue:          item.Queue,
			Status:         item.Status,
			Duplicate:      item.Duplicate,
			EnqueuedAt:     item.EnqueuedAt.UTC(),
			UpdatedAt:      item.UpdatedAt.UTC(),
		})
	}
	return models.WorkflowJobsSuccess{Jobs: items}, nil
}

// ExecutionHistory is the resolver for the executionHistory field.
func (r *queryResolver) ExecutionHistory(ctx context.Context, correlation models.SupervisorCorrelationInput, limit *int32) (models.ExecutionHistoryResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	history, err := r.Resolver.ControlPlaneService.ExecutionHistory(ctx, applicationcontrolplane.CorrelationFilter{RunID: correlation.RunID, TaskID: correlation.TaskID, JobID: correlation.JobID}, int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load execution history: %w", err)), nil
	}
	items := make([]*models.ExecutionHistoryRecord, 0, len(history))
	for _, item := range history {
		mappedJobKind, mapErr := toGraphJobKind(item.JobKind)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, &models.ExecutionHistoryRecord{
			RunID:          item.RunID,
			TaskID:         item.TaskID,
			JobID:          item.JobID,
			JobKind:        mappedJobKind,
			IdempotencyKey: item.IdempotencyKey,
			Step:           item.Step,
			Status:         string(item.Status),
			ErrorMessage:   nilIfEmpty(item.ErrorMessage),
			UpdatedAt:      item.UpdatedAt.UTC(),
		})
	}
	return models.ExecutionHistorySuccess{Records: items}, nil
}

// DeadLetterHistory is the resolver for the deadLetterHistory field.
func (r *queryResolver) DeadLetterHistory(ctx context.Context, queue *string, limit *int32) (models.DeadLetterHistoryResult, error) {
	if r == nil || r.Resolver == nil || r.Resolver.ControlPlaneService == nil {
		return models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "control-plane service is not configured"}, nil
	}
	history, err := r.Resolver.ControlPlaneService.DeadLetterHistory(ctx, derefString(queue), int32ToInt(limit))
	if err != nil {
		return graphErrorFromError(fmt.Errorf("load dead-letter history: %w", err)), nil
	}
	items := make([]*models.DeadLetterHistoryRecord, 0, len(history))
	for _, item := range history {
		mappedJobKind, mapErr := toGraphJobKind(item.JobKind)
		if mapErr != nil {
			return graphErrorFromError(mapErr), nil
		}
		items = append(items, &models.DeadLetterHistoryRecord{
			Queue:      item.Queue,
			TaskID:     item.TaskID,
			JobKind:    mappedJobKind,
			Action:     string(item.Action),
			LastError:  nilIfEmpty(item.LastError),
			Reason:     nilIfEmpty(item.Reason),
			Actor:      nilIfEmpty(item.Actor),
			OccurredAt: item.OccurredAt.UTC(),
		})
	}
	return models.DeadLetterHistorySuccess{Records: items}, nil
}

// SessionActivityStream is the resolver for the sessionActivityStream field.
func (r *subscriptionResolver) SessionActivityStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventSessionStarted, domainstream.EventSessionUpdated, domainstream.EventSessionCheckpointed, domainstream.EventSessionEnded, domainstream.EventSessionRecovered, domainstream.EventSessionHealth, domainstream.EventSessionInjectedPrompt:
			return true
		default:
			return false
		}
	})
}

// WorkflowExecutionStream is the resolver for the workflowExecutionStream field.
func (r *subscriptionResolver) WorkflowExecutionStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventToolStarted, domainstream.EventToolCompleted, domainstream.EventPermissionRequested, domainstream.EventPermissionDecided:
			return true
		default:
			return false
		}
	})
}

// AgentOutputStream is the resolver for the agentOutputStream field.
func (r *subscriptionResolver) AgentOutputStream(ctx context.Context, correlation models.SupervisorCorrelationInput, fromOffset *int32) (<-chan models.StreamEventResult, error) {
	return streamSubscription(ctx, r.Resolver.StreamService, correlation, fromOffset, func(eventType domainstream.EventType) bool {
		switch eventType {
		case domainstream.EventAgentChunk, domainstream.EventAgentTurnCompleted:
			return true
		default:
			return false
		}
	})
}

func streamSubscription(ctx context.Context, streamService *applicationstream.Service, correlation models.SupervisorCorrelationInput, fromOffset *int32, eventFilter func(domainstream.EventType) bool) (<-chan models.StreamEventResult, error) {
	if streamService == nil {
		return singleEventStream(models.GraphError{Code: models.GraphErrorCodeUnavailable, Message: "stream service is not configured"}), nil
	}
	output := make(chan models.StreamEventResult, 64)
	offset := int32ToInt(fromOffset)
	if offset < 0 {
		offset = 0
	}
	replay, err := streamService.ReplayFromOffset(ctx, uint64(offset), 500)
	if err != nil {
		return singleEventStream(graphErrorFromError(fmt.Errorf("replay stream events: %w", err))), nil
	}
	for _, event := range replay {
		if !matchesCorrelation(event, correlation) || !eventFilter(event.EventType) {
			continue
		}
		output <- models.StreamEventSuccess{Event: mapStreamEvent(event)}
	}
	_, live, cancel := streamService.Subscribe(256)
	go func() {
		defer cancel()
		defer close(output)
		for {
			select {
			case <-ctx.Done():
				return
			case event, open := <-live:
				if !open {
					return
				}
				if !matchesCorrelation(event, correlation) || !eventFilter(event.EventType) {
					continue
				}
				select {
				case output <- models.StreamEventSuccess{Event: mapStreamEvent(event)}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return output, nil
}

func matchesCorrelation(event domainstream.Event, correlation models.SupervisorCorrelationInput) bool {
	if strings.TrimSpace(correlation.RunID) != "" && strings.TrimSpace(event.CorrelationIDs.RunID) != strings.TrimSpace(correlation.RunID) {
		return false
	}
	if strings.TrimSpace(correlation.TaskID) != "" && strings.TrimSpace(event.CorrelationIDs.TaskID) != strings.TrimSpace(correlation.TaskID) {
		return false
	}
	if strings.TrimSpace(correlation.JobID) != "" && strings.TrimSpace(event.CorrelationIDs.JobID) != strings.TrimSpace(correlation.JobID) {
		return false
	}
	return true
}

func mapStreamEvent(event domainstream.Event) *models.StreamEvent {
	payload, err := json.Marshal(event.Payload)
	if err != nil {
		payload = []byte("{}")
	}
	return &models.StreamEvent{
		EventID:       event.EventID,
		StreamOffset:  uint64ToInt32(event.StreamOffset),
		OccurredAt:    event.OccurredAt.UTC(),
		RunID:         nilIfEmpty(event.CorrelationIDs.RunID),
		TaskID:        nilIfEmpty(event.CorrelationIDs.TaskID),
		JobID:         nilIfEmpty(event.CorrelationIDs.JobID),
		SessionID:     nilIfEmpty(event.CorrelationIDs.SessionID),
		CorrelationID: strings.TrimSpace(event.CorrelationIDs.CorrelationID),
		Source:        toGraphStreamEventSource(event.Source),
		EventType:     string(event.EventType),
		Payload:       string(payload),
	}
}

func singleEventStream(result models.StreamEventResult) <-chan models.StreamEventResult {
	output := make(chan models.StreamEventResult, 1)
	output <- result
	close(output)
	return output
}

func int32ToInt(value *int32) int {
	if value == nil {
		return 0
	}
	return int(*value)
}

func uint64ToInt32(value uint64) int32 {
	if value > math.MaxInt32 {
		return math.MaxInt32
	}
	return int32(value)
}

func toGraphJobKind(value taskengine.JobKind) (models.JobKind, error) {
	switch strings.TrimSpace(string(value)) {
	case string(taskengine.JobKindIngestionAgent):
		return models.JobKindIngestionAgentRun, nil
	case string(taskengine.JobKindAgentWorkflow):
		return models.JobKindAgentWorkflowRun, nil
	case string(taskengine.JobKindSCMWorkflow):
		return models.JobKindScmWorkflowRun, nil
	default:
		return "", fmt.Errorf("unsupported job kind %q", value)
	}
}

func toTrackerSourceKindString(kind models.TrackerSourceKind) string {
	switch kind {
	case models.TrackerSourceKindLocalJSON:
		return "local_json"
	case models.TrackerSourceKindGithubIssues:
		return "github_issues"
	case models.TrackerSourceKindJira:
		return "jira"
	case models.TrackerSourceKindLinear:
		return "linear"
	default:
		return ""
	}
}

func toGraphStreamEventSource(source domainstream.Source) models.StreamEventSource {
	switch source {
	case domainstream.SourceACP:
		return models.StreamEventSourceAcp
	case domainstream.SourceSessionFile:
		return models.StreamEventSourceSessionFile
	default:
		return models.StreamEventSourceWorker
	}
}

func derefString(value *string) string {
	if value == nil {
		return ""
	}
	return strings.TrimSpace(*value)
}

func nilIfEmpty(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}
	return &trimmed
}
