package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"agentic-orchestrator/internal/interface/graphql/models"
	"context"
)

// ScmSupportedOperations is the resolver for the scmSupportedOperations field.
func (r *queryResolver) ScmSupportedOperations(ctx context.Context) (models.ScmSupportedOperationsResult, error) {
	_ = ctx
	return models.ScmSupportedOperationsSuccess{Operations: allSupportedSCMOperations()}, nil
}
