package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"agentic-orchestrator/internal/interface/graphql/models"
	"context"
	"time"
)

// SupervisorDecisionHistory is the resolver for the supervisorDecisionHistory field.
func (r *queryResolver) SupervisorDecisionHistory(ctx context.Context, correlation models.SupervisorCorrelationInput) (models.SupervisorDecisionHistoryResult, error) {
	return loadSupervisorHistoryResult(ctx, r.Resolver.SupervisorService, correlation), nil
}

// SupervisorDecisionHistoryStream is the resolver for the supervisorDecisionHistoryStream field.
func (r *subscriptionResolver) SupervisorDecisionHistoryStream(ctx context.Context, correlation models.SupervisorCorrelationInput, intervalMs *int32) (<-chan models.SupervisorDecisionHistoryResult, error) {
	period := time.Second
	if intervalMs != nil && *intervalMs > 0 {
		period = time.Duration(*intervalMs) * time.Millisecond
	}
	stream := make(chan models.SupervisorDecisionHistoryResult, 1)
	stream <- loadSupervisorHistoryResult(ctx, r.Resolver.SupervisorService, correlation)
	go func() {
		ticker := time.NewTicker(period)
		defer ticker.Stop()
		defer close(stream)
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				result := loadSupervisorHistoryResult(ctx, r.Resolver.SupervisorService, correlation)
				select {
				case stream <- result:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return stream, nil
}
