package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	applicationsupervisor "agentic-orchestrator/internal/application/supervisor"
	domainsupervisor "agentic-orchestrator/internal/domain/supervisor"
	"agentic-orchestrator/internal/interface/graphql/models"
	"context"
	"fmt"
	"sort"
	"time"
)

func mapSupervisorDecision(decision domainsupervisor.Decision) *models.SupervisorDecision {
	entries := make([]*models.SupervisorDecisionMetadataEntry, 0, len(decision.Metadata))
	for key, value := range decision.Metadata {
		entries = append(entries, &models.SupervisorDecisionMetadataEntry{Key: key, Value: value})
	}
	sort.Slice(entries, func(left, right int) bool {
		return entries[left].Key < entries[right].Key
	})
	return &models.SupervisorDecision{
		RunID:         decision.CorrelationIDs.RunID,
		TaskID:        decision.CorrelationIDs.TaskID,
		JobID:         decision.CorrelationIDs.JobID,
		SignalType:    string(decision.SignalType),
		FromState:     string(decision.FromState),
		ToState:       string(decision.ToState),
		Action:        string(decision.Action),
		Reason:        string(decision.Reason),
		RuleName:      decision.RuleName,
		RulePriority:  int32(decision.RulePriority),
		OccurredAt:    decision.OccurredAt.UTC().Format(time.RFC3339Nano),
		AttentionZone: string(decision.AttentionZone),
		Attempt:       int32(decision.Attempt),
		MaxRetry:      int32(decision.MaxRetry),
		FailureClass:  string(decision.FailureClass),
		Metadata:      entries,
	}
}

func loadSupervisorHistory(ctx context.Context, supervisorService *applicationsupervisor.Service, correlation models.SupervisorCorrelationInput) ([]*models.SupervisorDecision, error) {
	if supervisorService == nil {
		return nil, fmt.Errorf("supervisor service is not configured")
	}
	history, err := supervisorService.History(ctx, domainsupervisor.CorrelationIDs{RunID: correlation.RunID, TaskID: correlation.TaskID, JobID: correlation.JobID})
	if err != nil {
		return nil, err
	}
	mapped := make([]*models.SupervisorDecision, 0, len(history))
	for _, decision := range history {
		mapped = append(mapped, mapSupervisorDecision(decision))
	}
	return mapped, nil
}

// SupervisorDecisionHistory is the resolver for the supervisorDecisionHistory field.
func (r *queryResolver) SupervisorDecisionHistory(ctx context.Context, correlation models.SupervisorCorrelationInput) ([]*models.SupervisorDecision, error) {
	return loadSupervisorHistory(ctx, r.Resolver.SupervisorService, correlation)
}

// SupervisorDecisionHistoryStream is the resolver for the supervisorDecisionHistoryStream field.
func (r *subscriptionResolver) SupervisorDecisionHistoryStream(ctx context.Context, correlation models.SupervisorCorrelationInput, intervalMs *int32) (<-chan []*models.SupervisorDecision, error) {
	period := time.Second
	if intervalMs != nil && *intervalMs > 0 {
		period = time.Duration(*intervalMs) * time.Millisecond
	}
	stream := make(chan []*models.SupervisorDecision, 1)
	initial, err := loadSupervisorHistory(ctx, r.Resolver.SupervisorService, correlation)
	if err != nil {
		return nil, err
	}
	stream <- initial
	go func() {
		ticker := time.NewTicker(period)
		defer ticker.Stop()
		defer close(stream)
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				history, historyErr := loadSupervisorHistory(ctx, r.Resolver.SupervisorService, correlation)
				if historyErr != nil {
					return
				}
				select {
				case stream <- history:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return stream, nil
}
